export const UPDATE_REVOLVING_BALANCES = 'UPDATE_REVOLVING_BALANCES';
export const UPDATE_INSTALMENT_DEBT = 'UPDATE_INSTALMENT_DEBT';
export const UPDATE_HELOC = 'UPDATE_HELOC';
export const UPDATE_HOUSING_COST = 'UPDATE_HOUSING_COST';

export const UPDATE_UDSR = 'UPDATE_UDSR';
export const UPDATE_GDSR = 'UPDATE_GDSR';
export const UPDATE_TDSR = 'UPDATE_TDSR';

export const GET_CALC_REQUEST = 'GET_CALC_REQUEST';
export const GET_CALC_SUCCESS = 'GET_CALC_SUCCESS';
export const GET_CALC_FAILURE = 'GET_CALC_FAILURE';

export const SAVE_CALC_REQUEST = 'SAVE_CALC_REQUEST';
export const SAVE_CALC_SUCCESS = 'SAVE_CALC_SUCCESS';
export const SAVE_CALC_FAILURE = 'SAVE_CALC_FAILURE';

export const CALC_RESET = 'CALC_RESET';
