// Decline Reasons
export const AFFORDABILITY = 'AFFORDABILITY';
export const MISREPRESENTATION_OF_INCOME = 'MISREPRESENTATION_OF_INCOME';
export const MISREPRESENTATION_OF_HOUSING_COST =
  'MISREPRESENTATION_OF_HOUSING_COST';
export const UNABLE_TO_VERIFY_INCOME = 'UNABLE_TO_VERIFY_INCOME';
export const UNEMPLOYED = 'UNEMPLOYED';
export const RETIRED = 'RETIRED';
export const NON_PR_OR_CITIZEN = 'NON_PR_OR_CITIZEN';
export const NEGATIVE_CREDIT_HISTORY_TRADE_RATINGS =
  'NEGATIVE_CREDIT_HISTORY_TRADE_RATINGS';
export const NEGATIVE_CREDIT_HISTORY_LARGE_NUMBER_NEGATIVE_TRADES =
  'EGATIVE_CREDIT_HISTORY_LARGE_NUMBER_NEGATIVE_TRADES';
export const PAST_BANKRUPTCY = 'PAST_BANKRUPTCY';
export const PAST_CONSUMER_PROPOSAL = 'PAST_CONSUMER_PROPOSAL';
export const BALANCE_IN_ARREARS_WITH_CRA = 'BALANCE_IN_ARREARS_WITH_CRA';
export const DISHONEST_OVER_PHONE = 'DISHONEST_OVER_PHONE';
export const POTENTIAL_FRAUDULENT_TRANSACTION_ID_MANIPULATED =
  'POTENTIAL_FRAUDULENT_TRANSACTION_ID_MANIPULATED';
export const POTENTIAL_FRAUDULENT_TRANSACTION_PAYSTUBS_MANIPULATED =
  'POTENTIAL_FRAUDULENT_TRANSACTION_PAYSTUBS_MANIPULATED';
export const POTENTIAL_FRAUDULENT_TRANSACTION_CHEQUE_MANIPULATED =
  'POTENTIAL_FRAUDULENT_TRANSACTION_CHEQUE_MANIPULATED';
export const POTENTIAL_FRAUDULENT_TRANSACTION_PHOTO_MANIPULATED =
  'POTENTIAL_FRAUDULENT_TRANSACTION_PHOTO_MANIPULATED';
export const POTENTIAL_FRAUDULENT_TRANSACTION_APPLIED_WITH_DIFFERENT_NAME =
  'POTENTIAL_FRAUDULENT_TRANSACTION_APPLIED_WITH_DIFFERENT_NAME';
export const POTENTIAL_FRAUDULENT_TRANSACTION_DELETED_ACCOUNTS =
  'POTENTIAL_FRAUDULENT_TRANSACTION_DELETED_ACCOUNTS';
export const SUSPICIOUS_BEHAVIOUR_MULTIPLE_APPLICATIONS_SAME_IP_SESSION =
  'SUSPICIOUS_BEHAVIOUR_MULTIPLE_APPLICATIONS_SAME_IP_SESSION';
export const NEGATIVE_SPENDING_BEHAVIOUR = 'NEGATIVE_SPENDING_BEHAVIOUR';
export const APPLICANT_ON_BLACKLIST = 'APPLICANT_ON_BLACKLIST';
export const DEROGATORY_INFORMATION_ON_BUREAU =
  'DEROGATORY_INFORMATION_ON_BUREAU';
export const FRAUD_WARNING_ON_BUREAU = 'FRAUD_WARNING_ON_BUREAU';
export const APPLYING_FOR_LOAN_ON_BEHALF_OF_SOMEONE_ELSE =
  'APPLYING_FOR_LOAN_ON_BEHALF_OF_SOMEONE_ELSE';
export const MEMBER_DOES_NOT_WANT_TO_PROCEED_WITH_APPLICATION =
  'MEMBER_DOES_NOT_WANT_TO_PROCEED_WITH_APPLICATION';
export const OTHER_DECLINED = 'OTHER_DECLINED';

// To On Hold/Freeze Reasons
export const FRAUD = 'FRAUD';
export const FSR_AND_FSA = 'FSR_AND_FSA';
export const OTHER_ON_HOLD = 'OTHER_ON_HOLD';

// Fraud Reasons
export const FRAUD_WARNING_ON_CREDIT_BUREAU = 'FRAUD_WARNING_ON_CREDIT_BUREAU';
export const EMAILAGE_EMAIL_CHECK = 'EMAILAGE_EMAIL_CHECK';
export const EMAILAGE_IP_CHECK = 'EMAILAGE_IP_CHECK';
export const NAME_NOT_MATCH_BANK_ACCT = 'NAME_NOT_MATCH_BANK_ACCT';
export const ADDRESS_NOT_MATCH_BUREAU = 'ADDRESS_NOT_MATCH_BUREAU';
export const LARGE_CASH_TRANSACTION = 'LARGE_CASH_TRANSACTION';
export const TOO_MANY_INQUIRIES = 'TOO_MANY_INQUIRIES';
export const NEW_MEMBER_VERIFICATION = 'NEW_MEMBER_VERIFICATION';
export const PEP_SELECTED = 'PEP_SELECTED';
export const THIRD_PARTY_SELECTED = 'THIRD_PARTY_SELECTED';
export const ID_UPLOADED = 'ID_UPLOADED';
export const OTHER_FRAUD = 'OTHER_FRAUD';

// permissions
export const EDIT_STATE_ACTIVE_TO_CANCELLED = 'EDIT_STATE_ACTIVE_TO_CANCELLED';
export const EDIT_STATE_ACTIVE_TO_DECLINED = 'EDIT_STATE_ACTIVE_TO_DECLINED';
export const EDIT_STATE_ACTIVE_TO_FRAUD = 'EDIT_STATE_ACTIVE_TO_FRAUD';
export const EDIT_STATE_ACTIVE_TO_ON_HOLD = 'EDIT_STATE_ACTIVE_TO_ON_HOLD';
export const EDIT_STATE_CANCELLED_TO_ACTIVE = 'EDIT_STATE_CANCELLED_TO_ACTIVE';
export const EDIT_STATE_CANCELLED_TO_FRAUD = 'EDIT_STATE_CANCELLED_TO_FRAUD';
export const EDIT_STATE_CANCELLED_TO_ON_HOLD =
  'EDIT_STATE_CANCELLED_TO_ON_HOLD';
export const EDIT_STATE_DECLINED_TO_ACTIVE = 'EDIT_STATE_DECLINED_TO_ACTIVE';
export const EDIT_STATE_DECLINED_TO_FRAUD = 'EDIT_STATE_DECLINED_TO_FRAUD';
export const EDIT_STATE_DECLINED_TO_ON_HOLD = 'EDIT_STATE_DECLINED_TO_ON_HOLD';
export const EDIT_STATE_FRAUD_TO_ACTIVE = 'EDIT_STATE_FRAUD_TO_ACTIVE';
export const EDIT_STATE_FRAUD_TO_DECLINED = 'EDIT_STATE_FRAUD_TO_DECLINED';
export const EDIT_STATE_FRAUD_TO_ON_HOLD = 'EDIT_STATE_FRAUD_TO_ON_HOLD';
export const EDIT_STATE_ON_HOLD_TO_ACTIVE = 'EDIT_STATE_ON_HOLD_TO_ACTIVE';
export const EDIT_STATE_ON_HOLD_TO_CANCELLED =
  'EDIT_STATE_ON_HOLD_TO_CANCELLED';
export const EDIT_STATE_ON_HOLD_TO_DECLINED = 'EDIT_STATE_ON_HOLD_TO_DECLINED';
export const EDIT_STATE_ON_HOLD_TO_FRAUD = 'EDIT_STATE_ON_HOLD_TO_FRAUD';
export const EDIT_STATE_EXPIRED_TO_ACTIVE = 'EDIT_STATE_EXPIRED_TO_ACTIVE';
export const EDIT_STATE_EXPIRED_TO_DECLINED = 'EDIT_STATE_EXPIRED_TO_DECLINED';
export const EDIT_STATE_EXPIRED_TO_ON_HOLD = 'EDIT_STATE_EXPIRED_TO_ON_HOLD';
export const EDIT_STATE_EXPIRED_TO_FRAUD = 'EDIT_STATE_EXPIRED_TO_FRAUD';

export const EDIT_UNDERWRITING_NOTE = 'EDIT_UNDERWRITING_NOTE';
