export default {
  'prs-AF': 'Afghanistan - Dari',
  'ps-AF': 'Afghanistan - Pashto',
  'sq-AL': 'Albania - Albanian',
  'ar-DZ': 'Algeria - Arabic',
  'tzm-DZ': 'Algeria - Tamazight (Latin)',
  'es-AR': 'Argentina - Spanish',
  'hy-AM': 'Armenia - Armenian',
  'en-AU': 'Australia - English',
  'de-AT': 'Austria - German',
  'az-AZ': 'Azerbaijan - Azeri (Cyrillic/Latin)',
  'ar-BH': 'Bahrain - Arabic',
  'bn-BD': 'Bangladesh - Bengali',
  'be-BY': 'Belarus - Belarusian',
  'nl-BE': 'Belgium - Dutch',
  'fr-BE': 'Belgium - French',
  'en-BZ': 'Belize - English',
  'es-VE': 'Bolivarian Republic of Venezuela - Spanish',
  'quz-BO': 'Bolivia - Quechua',
  'es-BO': 'Bolivia - Spanish',
  'bs-BA': 'Bosnia and Herzegovina - Bosnian (Cyrillic/Latin)',
  'hr-BA': 'Bosnia and Herzegovina - Croatian',
  'sr-BA': 'Bosnia and Herzegovina - Serbian (Cyrillic/Latin)',
  'pt-BR': 'Brazil - Portuguese',
  'ms-BN': 'Brunei Darussalam - Malay',
  'bg-BG': 'Bulgaria - Bulgarian',
  'km-KH': 'Cambodia - Khmer',
  'en-CA': 'Canada - English',
  'fr-CA': 'Canada - French',
  'iu-CA': 'Canada - Inuktitut (Latin/Syllabics)',
  'moh-CA': 'Canada - Mohawk',
  'en-029': 'Caribbean - English',
  'arn-CL': 'Chile - Mapudungun',
  'es-CL': 'Chile - Spanish',
  'es-CO': 'Colombia - Spanish',
  'es-CR': 'Costa Rica - Spanish',
  'hr-HR': 'Croatia - Croatian',
  'cs-CZ': 'Czech Republic - Czech',
  'da-DK': 'Denmark - Danish',
  'es-DO': 'Dominican Republic - Spanish',
  'quz-EC': 'Ecuador - Quechua',
  'es-EC': 'Ecuador - Spanish',
  'ar-EG': 'Egypt - Arabic',
  'es-SV': 'El Salvador - Spanish',
  'et-EE': 'Estonia - Estonian',
  'am-ET': 'Ethiopia - Amharic',
  'fo-FO': 'Faroe Islands - Faroese',
  'fi-FI': 'Finland - Finnish',
  'smn-FI': 'Finland - Sami (Inari)',
  'se-FI': 'Finland - Sami (Northern)',
  'sms-FI': 'Finland - Sami (Skolt)',
  'sv-FI': 'Finland - Swedish',
  'gsw-FR': 'France - Alsatian',
  'br-FR': 'France - Breton',
  'co-FR': 'France - Corsican',
  'fr-FR': 'France - French',
  'oc-FR': 'France - Occitan',
  'ka-GE': 'Georgia - Georgian',
  'de-DE': 'Germany - German',
  'dsb-DE': 'Germany - Lower Sorbian',
  'hsb-DE': 'Germany - Upper Sorbian',
  'el-GR': 'Greece - Greek',
  'kl-GL': 'Greenland - Greenlandic',
  'qut-GT': "Guatemala - K'iche",
  'es-GT': 'Guatemala - Spanish',
  'es-HN': 'Honduras - Spanish',
  'zh-HK': 'Hong Kong S.A.R. - Chinese (Traditional) Legacy',
  'hu-HU': 'Hungary - Hungarian',
  'is-IS': 'Iceland - Icelandic',
  'as-IN': 'India - Assamese',
  'bn-IN': 'India - Bengali',
  'en-IN': 'India - English',
  'gu-IN': 'India - Gujarati',
  'hi-IN': 'India - Hindi',
  'kn-IN': 'India - Kannada',
  'kok-IN': 'India - Konkani',
  'ml-IN': 'India - Malayalam',
  'mr-IN': 'India - Marathi',
  'or-IN': 'India - Oriya',
  'pa-IN': 'India - Punjabi',
  'sa-IN': 'India - Sanskrit',
  'ta-IN': 'India - Tamil',
  'te-IN': 'India - Telugu',
  'id-ID': 'Indonesia - Indonesian',
  'fa-IR': 'Iran - Persian',
  'ar-IQ': 'Iraq - Arabic',
  'en-IE': 'Ireland - English',
  'ga-IE': 'Ireland - Irish',
  'ur-PK': 'Islamic Republic of Pakistan - Urdu',
  'he-IL': 'Israel - Hebrew',
  'it-IT': 'Italy - Italian',
  'en-JM': 'Jamaica - English',
  'ja-JP': 'Japan - Japanese',
  'ar-JO': 'Jordan - Arabic',
  'kk-KZ': 'Kazakhstan - Kazakh',
  'sw-KE': 'Kenya - Kiswahili',
  'ko-KR': 'Korea - Korean',
  'ar-KW': 'Kuwait - Arabic',
  'ky-KG': 'Kyrgyzstan - Kyrgyz',
  'lo-LA': 'Lao P.D.R. - Lao',
  'lv-LV': 'Latvia - Latvian',
  'ar-LB': 'Lebanon - Arabic',
  'ar-LY': 'Libya - Arabic',
  'de-LI': 'Liechtenstein - German',
  'lt-LT': 'Lithuania - Lithuanian',
  'fr-LU': 'Luxembourg - French',
  'de-LU': 'Luxembourg - German',
  'lb-LU': 'Luxembourg - Luxembourgish',
  'zh-MO': 'Macao S.A.R. - Chinese (Traditional) Legacy',
  'mk-MK': 'Macedonia (FYROM) - Macedonian (FYROM)',
  'en-MY': 'Malaysia - English',
  'ms-MY': 'Malaysia - Malay',
  'dv-MV': 'Maldives - Divehi',
  'mt-MT': 'Malta - Maltese',
  'es-MX': 'Mexico - Spanish',
  'mn-MN': 'Mongolia - Mongolian (Cyrillic)',
  'sr-ME': 'Montenegro - Serbian (Cyrillic/Latin)',
  'ar-MA': 'Morocco - Arabic',
  'ne-NP': 'Nepal - Nepali',
  'nl-NL': 'Netherlands - Dutch',
  'fy-NL': 'Netherlands - Frisian',
  'en-NZ': 'New Zealand - English',
  'mi-NZ': 'New Zealand - Maori',
  'es-NI': 'Nicaragua - Spanish',
  'ha-NG': 'Nigeria - Hausa (Latin)',
  'ig-NG': 'Nigeria - Igbo',
  'yo-NG': 'Nigeria - Yoruba',
  'nb-NO': 'Norway - Norwegian (Bokmal)',
  'nn-NO': 'Norway - Norwegian (Nynorsk)',
  'smj-NO': 'Norway - Sami (Lule)',
  'se-NO': 'Norway - Sami (Northern)',
  'sma-NO': 'Norway - Sami (Southern)',
  'ar-OM': 'Oman - Arabic',
  'es-PA': 'Panama - Spanish',
  'es-PY': 'Paraguay - Spanish',
  'zh-CN': "People's Republic of China - Chinese (Simplified) Legacy",
  'mn-CN': "People's Republic of China - Mongolian (Traditional Mongolian)",
  'bo-CN': "People's Republic of China - Tibetan",
  'ug-CN': "People's Republic of China - Uyghur",
  'ii-CN': "People's Republic of China - Yi",
  'quz-PE': 'Peru - Quechua',
  'es-PE': 'Peru - Spanish',
  'fil-PH': 'Philippines - Filipino',
  'pl-PL': 'Poland - Polish',
  'pt-PT': 'Portugal - Portuguese',
  'fr-MC': 'Principality of Monaco - French',
  'es-PR': 'Puerto Rico - Spanish',
  'ar-QA': 'Qatar - Arabic',
  'en-PH': 'Republic of the Philippines - English',
  'ro-RO': 'Romania - Romanian',
  'ba-RU': 'Russia - Bashkir',
  'ru-RU': 'Russia - Russian',
  'tt-RU': 'Russia - Tatar',
  'sah-RU': 'Russia - Yakut',
  'rw-RW': 'Rwanda - Kinyarwanda',
  'ar-SA': 'Saudi Arabia - Arabic',
  'wo-SN': 'Senegal - Wolof',
  'sr-RS': 'Serbia - Serbian (Cyrillic/Latin)',
  'sr-CS': 'Serbia and Montenegro (Former) - Serbian (Cyrillic/Latin)',
  'zh-SG': 'Singapore - Chinese (Simplified) Legacy',
  'en-SG': 'Singapore - English',
  'sk-SK': 'Slovakia - Slovak',
  'sl-SI': 'Slovenia - Slovenian',
  'af-ZA': 'South Africa - Afrikaans',
  'en-ZA': 'South Africa - English',
  'xh-ZA': 'South Africa - isiXhosa',
  'zu-ZA': 'South Africa - isiZulu',
  'nso-ZA': 'South Africa - Sesotho sa Leboa',
  'tn-ZA': 'South Africa - Setswana',
  'eu-ES': 'Spain - Basque',
  'ca-ES': 'Spain - Catalan',
  'gl-ES': 'Spain - Galician',
  'es-ES': 'Spain - Spanish',
  'si-LK': 'Sri Lanka - Sinhala',
  'smj-SE': 'Sweden - Sami (Lule)',
  'se-SE': 'Sweden - Sami (Northern)',
  'sma-SE': 'Sweden - Sami (Southern)',
  'sv-SE': 'Sweden - Swedish',
  'fr-CH': 'Switzerland - French',
  'de-CH': 'Switzerland - German',
  'it-CH': 'Switzerland - Italian',
  'rm-CH': 'Switzerland - Romansh',
  'ar-SY': 'Syria - Arabic',
  'syr-SY': 'Syria - Syriac',
  'zh-TW': 'Taiwan - Chinese (Traditional) Legacy',
  'tg-TJ': 'Tajikistan - Tajik (Cyrillic)',
  'th-TH': 'Thailand - Thai',
  'en-TT': 'Trinidad and Tobago - English',
  'ar-TN': 'Tunisia - Arabic',
  'tr-TR': 'Turkey - Turkish',
  'tk-TM': 'Turkmenistan - Turkmen',
  'ar-AE': 'U.A.E. - Arabic',
  'uk-UA': 'Ukraine - Ukrainian',
  'en-GB': 'United Kingdom - English',
  'gd-GB': 'United Kingdom - Scottish Gaelic',
  'cy-GB': 'United Kingdom - Welsh',
  'en-US': 'United States - English',
  'es-US': 'United States - Spanish',
  'es-UY': 'Uruguay - Spanish',
  'uz-UZ': 'Uzbekistan - Uzbek (Cyrillic/Latin)',
  'vi-VN': 'Vietnam - Vietnamese',
  'ar-YE': 'Yemen - Arabic',
  'en-ZW': 'Zimbabwe - English',
};
