export default [
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Consultant-Agricultural Reps',
    value: 'Consultant-Agricultural Reps',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Inspector-Agri/Fish Products',
    value: 'Inspector-Agri/Fish Products',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Specialist-Landscape/Horticul',
    value: 'Specialist-Landscape/Horticul',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Operator-Grain Elevator',
    value: 'Operator-Grain Elevator',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Farmer/Farm Manager',
    value: 'Farmer/Farm Manager',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Agricultural/Related Service',
    value: 'Agricultural/Related Service',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Farm Mgr/Livestock Worker',
    value: 'Farm Mgr/Livestock Worker',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Operator-Nursery/Greenhouse',
    value: 'Operator-Nursery/Greenhouse',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Landscaping/Grounds Mtce',
    value: 'Landscaping/Grounds Mtce',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Mgr-Landscape/Horticulture',
    value: 'Mgr-Landscape/Horticulture',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Mgr-Aquaculture Operator',
    value: 'Mgr-Aquaculture Operator',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'General Farm Worker ',
    value: 'General Farm Worker ',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Nursery/Greenhouse Worker',
    value: 'Nursery/Greenhouse Worker',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Harvesting Labourer',
    value: 'Harvesting Labourer',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Aquaculture/Marine Harvest',
    value: 'Aquaculture/Marine Harvest',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Farm-Bee Keeper',
    value: 'Farm-Bee Keeper',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Grain Farmer',
    value: 'Grain Farmer',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Mixed Farmer',
    value: 'Mixed Farmer',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Rancher',
    value: 'Rancher',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Bus Owner-Agric Related',
    value: 'Bus Owner-Agric Related',
  },
  {
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Bus Owner-Landscape/Grounds',
    value: 'Bus Owner-Landscape/Grounds',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Mgr-Engineering',
    value: 'Mgr-Engineering',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Mgr-Architecture/Science',
    value: 'Mgr-Architecture/Science',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Civil',
    value: 'Engineer-Civil',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Mechanical',
    value: 'Engineer-Mechanical',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Electrical',
    value: 'Engineer-Electrical',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Chemical',
    value: 'Engineer-Chemical',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Industrial/Manuf',
    value: 'Engineer-Industrial/Manuf',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Meta/Materials',
    value: 'Engineer-Meta/Materials',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Aerospace',
    value: 'Engineer-Aerospace',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Engineer-Other',
    value: 'Engineer-Other',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Architect',
    value: 'Architect',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Architect-Landscape',
    value: 'Architect-Landscape',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Urban/Use Planner',
    value: 'Urban/Use Planner',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Civil Engineering',
    value: 'Technician-Civil Engineering',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Mech Engineering',
    value: 'Technician-Mech Engineering',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Indus Engineering',
    value: 'Technician-Indus Engineering',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Electrical Engineer',
    value: 'Technician-Electrical Engineer',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Industrial Instrum',
    value: 'Technician-Industrial Instrum',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Architectural',
    value: 'Technician-Architectural',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Designer-Industrial',
    value: 'Designer-Industrial',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Technician-Drafting',
    value: 'Technician-Drafting',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Inspctr-NonDestruct Tester',
    value: 'Inspctr-NonDestruct Tester',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Inspctr-Engineer/Regulator',
    value: 'Inspctr-Engineer/Regulator',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Officer-Engineer/Water Trans',
    value: 'Officer-Engineer/Water Trans',
  },
  {
    category: 'Architecture & Engineering',
    name: 'Bus Owner-Architecture',
    value: 'Bus Owner-Architecture',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Mgr-Broadcasting/Perform Arts',
    value: 'Mgr-Broadcasting/Perform Arts',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Planner-Conference/Event',
    value: 'Planner-Conference/Event',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Producer/Director/Choreograp',
    value: 'Producer/Director/Choreograp',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Desktop Publish Oper/Related',
    value: 'Desktop Publish Oper/Related',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Collector',
    value: 'Collector',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Conservator/Curator',
    value: 'Conservator/Curator',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Author/Writer',
    value: 'Author/Writer',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Editor',
    value: 'Editor',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Journalist',
    value: 'Journalist',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Public Relations/Communication',
    value: 'Public Relations/Communication',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Conductor/Composer',
    value: 'Conductor/Composer',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Operator-Printing Machine',
    value: 'Operator-Printing Machine',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Musician/Singer',
    value: 'Musician/Singer',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Dancer',
    value: 'Dancer',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Actors/Comedians',
    value: 'Actors/Comedians',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Photographer',
    value: 'Photographer',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Operator-Film/Video Camera',
    value: 'Operator-Film/Video Camera',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Technician-Graphic Arts',
    value: 'Technician-Graphic Arts',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Technician-Broadcast',
    value: 'Technician-Broadcast',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Technician-Audio/Video Record',
    value: 'Technician-Audio/Video Record',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Motion Pic/Broadcast/Perf Arts',
    value: 'Motion Pic/Broadcast/Perf Arts',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Mgr Motion Pic/Broad/Perf Arts',
    value: 'Mgr Motion Pic/Broad/Perf Arts',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Announcer/Other Broadcaster',
    value: 'Announcer/Other Broadcaster',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Performer-Other',
    value: 'Performer-Other',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Designer-Graphic/Illustrator',
    value: 'Designer-Graphic/Illustrator',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Designer-Interior',
    value: 'Designer-Interior',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Designer-Theatre/Fashion',
    value: 'Designer-Theatre/Fashion',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Artisan/Craftsperson',
    value: 'Artisan/Craftsperson',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Attendent-Casino',
    value: 'Attendent-Casino',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Consult-Image/Social/Other',
    value: 'Consult-Image/Social/Other',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Mgr-Printing/Related',
    value: 'Mgr-Printing/Related',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Operator-Printing Press',
    value: 'Operator-Printing Press',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Camera/Platemaking Prepress',
    value: 'Camera/Platemaking Prepress',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Photographic/Film Processor',
    value: 'Photographic/Film Processor',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Bus Owner-Media',
    value: 'Bus Owner-Media',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Bus Owner-Arts & Design',
    value: 'Bus Owner-Arts & Design',
  },
  {
    category: 'Arts, Design, Entertainment & Media',
    name: 'Bus Owner-Entertainment',
    value: 'Bus Owner-Entertainment',
  },
  {
    category: 'Business & Financial',
    name: 'Mgr-Financial',
    value: 'Mgr-Financial',
  },
  {
    category: 'Business & Financial',
    name: 'Mgr-Banking/Credit',
    value: 'Mgr-Banking/Credit',
  },
  {
    category: 'Business & Financial',
    name: 'Branch sales/Call Centre agent',
    value: 'Branch sales/Call Centre agent',
  },
  {
    category: 'Business & Financial',
    name: 'Mgr-Other Bus. Service',
    value: 'Mgr-Other Bus. Service',
  },
  {
    category: 'Business & Financial',
    name: 'Fin-Auditor/Accountant',
    value: 'Fin-Auditor/Accountant',
  },
  {
    category: 'Business & Financial',
    name: 'Fin-Investment Analyst',
    value: 'Fin-Investment Analyst',
  },
  {
    category: 'Business & Financial',
    name: 'Fin-Investment Dealer/Broker',
    value: 'Fin-Investment Dealer/Broker',
  },
  {
    category: 'Business & Financial',
    name: 'Officer-Other Financial',
    value: 'Officer-Other Financial',
  },
  {
    category: 'Business & Financial',
    name: 'Supervisor-Finance Insurance',
    value: 'Supervisor-Finance Insurance',
  },
  {
    category: 'Business & Financial',
    name: 'Supervisor-Record/Dist/Sched',
    value: 'Supervisor-Record/Dist/Sched',
  },
  { category: 'Business & Financial', name: 'Bookkeeper', value: 'Bookkeeper' },
  {
    category: 'Business & Financial',
    name: 'Officer-Loan',
    value: 'Officer-Loan',
  },
  {
    category: 'Business & Financial',
    name: 'Insurance Underwriter',
    value: 'Insurance Underwriter',
  },
  {
    category: 'Business & Financial',
    name: 'Clerk-Banking/Ins/Other Financ',
    value: 'Clerk-Banking/Ins/Other Financ',
  },
  {
    category: 'Business & Financial',
    name: 'Math/Statistics/Actuary',
    value: 'Math/Statistics/Actuary',
  },
  {
    category: 'Business & Financial',
    name: 'Analyst-Econ Policy Research',
    value: 'Analyst-Econ Policy Research',
  },
  {
    category: 'Business & Financial',
    name: 'Consultant-Bus. Dev/Marketing',
    value: 'Consultant-Bus. Dev/Marketing',
  },
  {
    category: 'Business & Financial',
    name: 'Consult-Social Policy Research',
    value: 'Consult-Social Policy Research',
  },
  {
    category: 'Business & Financial',
    name: 'Bus Owner-Financial',
    value: 'Bus Owner-Financial',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Hairstylist/Barber',
    value: 'Hairstylist/Barber',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Babysitter/Nanny',
    value: 'Babysitter/Nanny',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Esthetician/Electrologist',
    value: 'Esthetician/Electrologist',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Pet Groomer/Animal Care',
    value: 'Pet Groomer/Animal Care',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Other Personal Service',
    value: 'Other Personal Service',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Jeweller/Watch Repairer',
    value: 'Jeweller/Watch Repairer',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Stay-at-home Parent',
    value: 'Stay-at-home Parent',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Child Care Provider/Youth Work',
    value: 'Child Care Provider/Youth Work',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Bus Owner-Esthetics',
    value: 'Bus Owner-Esthetics',
  },
  {
    category: 'Child Care & Personal Services',
    name: 'Bus Owner-Child Care',
    value: 'Bus Owner-Child Care',
  },
  {
    category: 'Community/Spiritual Services',
    name: 'Counsellor-Family/Marriage',
    value: 'Counsellor-Family/Marriage',
  },
  {
    category: 'Community/Spiritual Services',
    name: 'Minister of Religion',
    value: 'Minister of Religion',
  },
  {
    category: 'Community/Spiritual Services',
    name: 'Community/Social Service',
    value: 'Community/Social Service',
  },
  {
    category: 'Community/Spiritual Services',
    name: 'Counsellor-Employment',
    value: 'Counsellor-Employment',
  },
  {
    category: 'Community/Spiritual Services',
    name: 'Religious-Other',
    value: 'Religious-Other',
  },
  {
    category: 'Community/Spiritual Services',
    name: 'Funeral Director/Embalmer',
    value: 'Funeral Director/Embalmer',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Mgr-Computer/Info Sys',
    value: 'Mgr-Computer/Info Sys',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Engineer-Computer',
    value: 'Engineer-Computer',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Consultant-Information Systems',
    value: 'Consultant-Information Systems',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Analyst-Database/Data Admin',
    value: 'Analyst-Database/Data Admin',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Engineer-Software Designer',
    value: 'Engineer-Software Designer',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Computer Program/Interactive',
    value: 'Computer Program/Interactive',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Designer-Web Developer',
    value: 'Designer-Web Developer',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-Electronic Service',
    value: 'Technician-Electronic Service',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-Computer Network',
    value: 'Technician-Computer Network',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-User Support',
    value: 'Technician-User Support',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-Systems Testing',
    value: 'Technician-Systems Testing',
  },
  {
    category: 'Computer Technology & Other Computer Related',
    name: 'Bus Owner-Computer Related',
    value: 'Bus Owner-Computer Related',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Mgr-Construction',
    value: 'Mgr-Construction',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Construction Estimator',
    value: 'Construction Estimator',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Residental Home Build/Reno',
    value: 'Residental Home Build/Reno',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Inspector-Construction',
    value: 'Inspector-Construction',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Elec Trades',
    value: 'Contractor-Mgr/Elec Trades',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Pipefitting',
    value: 'Contractor-Mgr/Pipefitting',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Carpentry',
    value: 'Contractor-Mgr/Carpentry',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Heavy Const',
    value: 'Contractor-Mgr/Heavy Const',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Other Const',
    value: 'Contractor-Mgr/Other Const',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Electrician',
    value: 'Electrician',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Electrician-Industrial',
    value: 'Electrician-Industrial',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Electrician-Power System',
    value: 'Electrician-Power System',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Plumber',
    value: 'Plumber',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Steam/Pipe fit/Sprinkler Inst',
    value: 'Steam/Pipe fit/Sprinkler Inst',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Gas Fitter',
    value: 'Gas Fitter',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Operator-Welder/Related Mach',
    value: 'Operator-Welder/Related Mach',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Carpenter',
    value: 'Carpenter',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Cabinetmaker',
    value: 'Cabinetmaker',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Bricklayer',
    value: 'Bricklayer',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Concrete Finisher',
    value: 'Concrete Finisher',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Tilesetter',
    value: 'Tilesetter',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Plasterer/Drywall/Finisher',
    value: 'Plasterer/Drywall/Finisher',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Roofer/Shingler',
    value: 'Roofer/Shingler',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Insulator',
    value: 'Insulator',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Painter/Decorator',
    value: 'Painter/Decorator',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Floor Covering Installer',
    value: 'Floor Covering Installer',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Construct Millwright/Industri',
    value: 'Construct Millwright/Industri',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Refrig/Air Conditioning Mech',
    value: 'Refrig/Air Conditioning Mech',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Elevator Constructor/Mech',
    value: 'Elevator Constructor/Mech',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Oil/Solid Fuel Heating Mech',
    value: 'Oil/Solid Fuel Heating Mech',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Engineer-Stationary/Operator',
    value: 'Engineer-Stationary/Operator',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Operator-Power Systems/Stat',
    value: 'Operator-Power Systems/Stat',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Operator-Crane',
    value: 'Operator-Crane',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Other Trade/Related Occup',
    value: 'Other Trade/Related Occup',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Operator-Heavy Equipment',
    value: 'Operator-Heavy Equipment',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Res/Comm Installer/Servicer',
    value: 'Res/Comm Installer/Servicer',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Construct Trade Labourer',
    value: 'Construct Trade Labourer',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Other Trade Helper/Labourer',
    value: 'Other Trade Helper/Labourer',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Concrete/Clay/Stone Forming Op',
    value: 'Concrete/Clay/Stone Forming Op',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Bus Owner-Construction',
    value: 'Bus Owner-Construction',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Stone Mason',
    value: 'Stone Mason',
  },
  {
    category: 'Construction & Construction Trades',
    name: 'Bus Owner-Trade',
    value: 'Bus Owner-Trade',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Mgr-Postal/Courier Service',
    value: 'Mgr-Postal/Courier Service',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Supervisor-Mail/Distribution',
    value: 'Supervisor-Mail/Distribution',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Clerk-Mail/Postal/Related',
    value: 'Clerk-Mail/Postal/Related',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Letter Carrier',
    value: 'Letter Carrier',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Courier/Door-to-Door Dist',
    value: 'Courier/Door-to-Door Dist',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Shipper/Receiver',
    value: 'Shipper/Receiver',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Truck Driver',
    value: 'Truck Driver',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Delivery/Courier Svc Driver',
    value: 'Delivery/Courier Svc Driver',
  },
  {
    category: 'Delivery & Postal Services',
    name: 'Bus Owner-Delivery Service',
    value: 'Bus Owner-Delivery Service',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Admin-Post-Second/Vocation',
    value: 'Admin-Post-Second/Vocation',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Sch Principal/Admin Elem/Sec',
    value: 'Sch Principal/Admin Elem/Sec',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Mgr-Library/Museum/Art',
    value: 'Mgr-Library/Museum/Art',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Supervisor-Library/Correspond',
    value: 'Supervisor-Library/Correspond',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Clerk-Library',
    value: 'Clerk-Library',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Instructor-Air Pilot',
    value: 'Instructor-Air Pilot',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'University Professor',
    value: 'University Professor',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Teacher-Post-Second/Research',
    value: 'Teacher-Post-Second/Research',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Teacher-College/Oth Vocation',
    value: 'Teacher-College/Oth Vocation',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Teacher-Secondary School',
    value: 'Teacher-Secondary School',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Teacher-Elementary Sch/Kinder',
    value: 'Teacher-Elementary Sch/Kinder',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Counsellor-Education',
    value: 'Counsellor-Education',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Consult-Educ Policy Research',
    value: 'Consult-Educ Policy Research',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Teacher-Early Childhood/Asst',
    value: 'Teacher-Early Childhood/Asst',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Instructor-Per with Disabled',
    value: 'Instructor-Per with Disabled',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Instructor-Other',
    value: 'Instructor-Other',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Librarian',
    value: 'Librarian',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Archivist',
    value: 'Archivist',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Assistant-Library/Archive Tech',
    value: 'Assistant-Library/Archive Tech',
  },
  {
    category: 'Education, Teaching & Library',
    name: 'Assistant-Elem/Second School',
    value: 'Assistant-Elem/Second School',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Primary Prod (exc Agri)',
    value: 'Mgr-Primary Prod (exc Agri)',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Forestry Professional',
    value: 'Forestry Professional',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Engineer-Mining',
    value: 'Engineer-Mining',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Technician-Forestry',
    value: 'Technician-Forestry',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Officer-Conservation/Fishery',
    value: 'Officer-Conservation/Fishery',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Driller/Blast/Mine/Quarry',
    value: 'Driller/Blast/Mine/Quarry',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Longshore Worker',
    value: 'Longshore Worker',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Logging/Forestry',
    value: 'Mgr-Logging/Forestry',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Mining/Quarrying',
    value: 'Mgr-Mining/Quarrying',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Development Miner',
    value: 'Development Miner',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Logging Machinery',
    value: 'Operator-Logging Machinery',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Officer-Fishing Masters',
    value: 'Officer-Fishing Masters',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Fishing Vessel Skipper/Fisher',
    value: 'Fishing Vessel Skipper/Fisher',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Underground Mine Worker',
    value: 'Underground Mine Worker',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Chain Saw/Skidder',
    value: 'Operator-Chain Saw/Skidder',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Silviculture/Forestry Worker',
    value: 'Silviculture/Forestry Worker',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Fishing Vessel Deckhand',
    value: 'Fishing Vessel Deckhand',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Trapper/Hunter',
    value: 'Trapper/Hunter',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Mine Labourer',
    value: 'Mine Labourer',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Logging/Forestry Labourer',
    value: 'Logging/Forestry Labourer',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Mineral/Metal Processing',
    value: 'Mgr-Mineral/Metal Processing',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Forest Products Process',
    value: 'Mgr-Forest Products Process',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Pulping Control',
    value: 'Operator-Pulping Control',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Tester-Mineral Metal Process',
    value: 'Tester-Mineral Metal Process',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Sawmill Machine',
    value: 'Operator-Sawmill Machine',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Pulp Mill Machine',
    value: 'Operator-Pulp Mill Machine',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Oper-Wood Process Other',
    value: 'Oper-Wood Process Other',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Lumber Grader/Other Wood',
    value: 'Lumber Grader/Other Wood',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Fish Plant Worker',
    value: 'Fish Plant Worker',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Woodworking Machine',
    value: 'Operator-Woodworking Machine',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Labourer WoodPulpPaper Process',
    value: 'Labourer WoodPulpPaper Process',
  },
  {
    category: 'Fishing, Forestry & Mining',
    name: 'Labourer-Fish Processing',
    value: 'Labourer-Fish Processing',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Mgr-Restaurant/Food Service',
    value: 'Mgr-Restaurant/Food Service',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Mgr-Food Service',
    value: 'Mgr-Food Service',
  },
  { category: 'Food Preparation & Serving', name: 'Chef', value: 'Chef' },
  { category: 'Food Preparation & Serving', name: 'Cook', value: 'Cook' },
  {
    category: 'Food Preparation & Serving',
    name: 'Butcher/Meat Cutter/Fish',
    value: 'Butcher/Meat Cutter/Fish',
  },
  { category: 'Food Preparation & Serving', name: 'Baker', value: 'Baker' },
  {
    category: 'Food Preparation & Serving',
    name: 'Bartender',
    value: 'Bartender',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Coffee Server/Barista',
    value: 'Coffee Server/Barista',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Food/Beverage Server',
    value: 'Food/Beverage Server',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Clerk-Grocery/Store Stocker',
    value: 'Clerk-Grocery/Store Stocker',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Food Counter Attend/Kitchen',
    value: 'Food Counter Attend/Kitchen',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Mgr-Food/Bev/Tobacco Process',
    value: 'Mgr-Food/Bev/Tobacco Process',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'MachOper/Food/Beverage Process',
    value: 'MachOper/Food/Beverage Process',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Butcher/Meat Cutter/Poultry',
    value: 'Butcher/Meat Cutter/Poultry',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Tester/Grader/Food/Bev Proc',
    value: 'Tester/Grader/Food/Bev Proc',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Labourer Food/Beverage/Tobacco',
    value: 'Labourer Food/Beverage/Tobacco',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Business Owner-Food Svc',
    value: 'Business Owner-Food Svc',
  },
  {
    category: 'Food Preparation & Serving',
    name: 'Waiter/Waitress',
    value: 'Waiter/Waitress',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Mgr-Govt/Admin-Health/Soc',
    value: 'Mgr-Govt/Admin-Health/Soc',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Legislator/Political Leader',
    value: 'Legislator/Political Leader',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Mgr-Govt-Econ Policy',
    value: 'Mgr-Govt-Econ Policy',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Mgr-Govt/Admin-Educ Policy',
    value: 'Mgr-Govt/Admin-Educ Policy',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Social Worker',
    value: 'Social Worker',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Social Science-Other',
    value: 'Social Science-Other',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Translator/Interpreter',
    value: 'Translator/Interpreter',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Oper-Public Works Mtce equip',
    value: 'Oper-Public Works Mtce equip',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Waterworks/Gas Mtce Worker',
    value: 'Waterworks/Gas Mtce Worker',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Public Works/Mtce Labourer',
    value: 'Public Works/Mtce Labourer',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Operator-Water/Waste Plant',
    value: 'Operator-Water/Waste Plant',
  },
  {
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Aboriginal Affairs',
    value: 'Aboriginal Affairs',
  },
  {
    category: 'Healthcare',
    name: 'Secretary-Medical',
    value: 'Secretary-Medical',
  },
  {
    category: 'Healthcare',
    name: 'Other Prof Occup-Phys Science',
    value: 'Other Prof Occup-Phys Science',
  },
  {
    category: 'Healthcare',
    name: 'Inspector-Env Health/Safety',
    value: 'Inspector-Env Health/Safety',
  },
  {
    category: 'Healthcare',
    name: 'Physician-Specialist',
    value: 'Physician-Specialist',
  },
  {
    category: 'Healthcare',
    name: 'Physician-General/Family',
    value: 'Physician-General/Family',
  },
  { category: 'Healthcare', name: 'Dentist', value: 'Dentist' },
  { category: 'Healthcare', name: 'Mgr-Health Care', value: 'Mgr-Health Care' },
  { category: 'Healthcare', name: 'Veterinarian', value: 'Veterinarian' },
  { category: 'Healthcare', name: 'Optometrist', value: 'Optometrist' },
  {
    category: 'Healthcare',
    name: 'Other Health Diagnose/Treating',
    value: 'Other Health Diagnose/Treating',
  },
  { category: 'Healthcare', name: 'Pharmacist', value: 'Pharmacist' },
  {
    category: 'Healthcare',
    name: 'Dietitian/Nutritionist',
    value: 'Dietitian/Nutritionist',
  },
  {
    category: 'Healthcare',
    name: 'Audiologist/Speech Language',
    value: 'Audiologist/Speech Language',
  },
  { category: 'Healthcare', name: 'Physiotherapist', value: 'Physiotherapist' },
  {
    category: 'Healthcare',
    name: 'Medical Transcriptionist',
    value: 'Medical Transcriptionist',
  },
  { category: 'Healthcare', name: 'Occup Therapist', value: 'Occup Therapist' },
  {
    category: 'Healthcare',
    name: 'Other in Therapy/Assessment',
    value: 'Other in Therapy/Assessment',
  },
  {
    category: 'Healthcare',
    name: 'Nurse-Head/Supervisor',
    value: 'Nurse-Head/Supervisor',
  },
  {
    category: 'Healthcare',
    name: 'Nurse-Registered',
    value: 'Nurse-Registered',
  },
  {
    category: 'Healthcare',
    name: 'Assistant-Medical Lab. Tech',
    value: 'Assistant-Medical Lab. Tech',
  },
  {
    category: 'Healthcare',
    name: 'Technician-Medical Laboratory',
    value: 'Technician-Medical Laboratory',
  },
  {
    category: 'Healthcare',
    name: 'Technician-Vet/Animal Health',
    value: 'Technician-Vet/Animal Health',
  },
  {
    category: 'Healthcare',
    name: 'Respiratory/Perfusion/Cardio',
    value: 'Respiratory/Perfusion/Cardio',
  },
  {
    category: 'Healthcare',
    name: 'Technologist-Medical Radiation',
    value: 'Technologist-Medical Radiation',
  },
  {
    category: 'Healthcare',
    name: 'Medical Sonographer',
    value: 'Medical Sonographer',
  },
  {
    category: 'Healthcare',
    name: 'Technologist-Cardiology',
    value: 'Technologist-Cardiology',
  },
  {
    category: 'Healthcare',
    name: 'Electroencephalographic/Other',
    value: 'Electroencephalographic/Other',
  },
  {
    category: 'Healthcare',
    name: 'Technologist-Other Medical',
    value: 'Technologist-Other Medical',
  },
  { category: 'Healthcare', name: 'Denturist', value: 'Denturist' },
  {
    category: 'Healthcare',
    name: 'Dental Hygienist/Therapist',
    value: 'Dental Hygienist/Therapist',
  },
  {
    category: 'Healthcare',
    name: 'Technician-Dental/Lab Bench',
    value: 'Technician-Dental/Lab Bench',
  },
  { category: 'Healthcare', name: 'Optician', value: 'Optician' },
  {
    category: 'Healthcare',
    name: 'Midwife/Natural Healing',
    value: 'Midwife/Natural Healing',
  },
  {
    category: 'Healthcare',
    name: 'Nurse-Licensed Practical',
    value: 'Nurse-Licensed Practical',
  },
  {
    category: 'Healthcare',
    name: 'Attendant-Ambulance',
    value: 'Attendant-Ambulance',
  },
  {
    category: 'Healthcare',
    name: 'Other Therapy/Assessment',
    value: 'Other Therapy/Assessment',
  },
  {
    category: 'Healthcare',
    name: 'Assistant-Dental',
    value: 'Assistant-Dental',
  },
  {
    category: 'Healthcare',
    name: 'Nurse-Aide/Orderly',
    value: 'Nurse-Aide/Orderly',
  },
  {
    category: 'Healthcare',
    name: 'Health Service-Other Support',
    value: 'Health Service-Other Support',
  },
  { category: 'Healthcare', name: 'Psychologist', value: 'Psychologist' },
  {
    category: 'Healthcare',
    name: 'Consult-Health Policy Research',
    value: 'Consult-Health Policy Research',
  },
  {
    category: 'Healthcare',
    name: 'Bus Owner-Health Services',
    value: 'Bus Owner-Health Services',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Executive Housekeeper',
    value: 'Executive Housekeeper',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Mgr-Dry Cleaning/Laundry',
    value: 'Mgr-Dry Cleaning/Laundry',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Mgr-Cleaning Supervisor',
    value: 'Mgr-Cleaning Supervisor',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Visiting Homemaker/Housekeep',
    value: 'Visiting Homemaker/Housekeep',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Cleaner-Light Duty',
    value: 'Cleaner-Light Duty',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Cleaner-Specialized',
    value: 'Cleaner-Specialized',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Janitor/Caretaker',
    value: 'Janitor/Caretaker',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Dry Cleaning/Laundry Occup',
    value: 'Dry Cleaning/Laundry Occup',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Ironing/Pressing/Finishing Occ',
    value: 'Ironing/Pressing/Finishing Occ',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Pest Controller/Fumigator',
    value: 'Pest Controller/Fumigator',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Bus Owner-Janitorial/Clean',
    value: 'Bus Owner-Janitorial/Clean',
  },
  {
    category: 'Janitorial & Cleaning Services',
    name: 'Septic & Garbage Services',
    value: 'Septic & Garbage Services',
  },
  { category: 'Legal', name: 'Secretary-Legal', value: 'Secretary-Legal' },
  {
    category: 'Legal',
    name: 'Court Recorder/Med Transcript',
    value: 'Court Recorder/Med Transcript',
  },
  { category: 'Legal', name: 'Clerk-Court', value: 'Clerk-Court' },
  { category: 'Legal', name: 'Judge-Test', value: 'Judge-Test' },
  {
    category: 'Legal',
    name: 'Paralegal/Related Occupation',
    value: 'Paralegal/Related Occupation',
  },
  {
    category: 'Legal',
    name: 'Lawyer/Quebec Notary',
    value: 'Lawyer/Quebec Notary',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Facility Oper/Mtce',
    value: 'Mgr-Facility Oper/Mtce',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Manufacturing',
    value: 'Mgr-Manufacturing',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr/Machinist/Related Occup',
    value: 'Mgr/Machinist/Related Occup',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Contractor-Mgr/Metal Forming',
    value: 'Contractor-Mgr/Metal Forming',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Machinist/Tooling',
    value: 'Inspector-Machinist/Tooling',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Tool/Die Maker',
    value: 'Tool/Die Maker',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Sheet Metal Worker',
    value: 'Sheet Metal Worker',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Boilermaker',
    value: 'Boilermaker',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Struct Metal/Platework Fabric',
    value: 'Struct Metal/Platework Fabric',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Ironworker',
    value: 'Ironworker',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Blacksmith/Die Setter',
    value: 'Blacksmith/Die Setter',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Machine Fitter',
    value: 'Machine Fitter',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Material Handler',
    value: 'Material Handler',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Plastic/Rubber Products',
    value: 'Mgr-Plastic/Rubber Products',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Motor Veh/Mach Rep Assem',
    value: 'Mgr-Motor Veh/Mach Rep Assem',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Electronics Manufacture',
    value: 'Mgr-Electronics Manufacture',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Elec Products Manufacture',
    value: 'Mgr-Elec Products Manufacture',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Other Mech/Metal',
    value: 'Mgr-Other Mech/Metal',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Other Prod Manufacture',
    value: 'Mgr-Other Prod Manufacture',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Papermaking/Coating',
    value: 'Operator-Papermaking/Coating',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mineral/Metal Process Manufact',
    value: 'Mineral/Metal Process Manufact',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Oper-Glass Forming/Finishing',
    value: 'Oper-Glass Forming/Finishing',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Plastics Process Mach',
    value: 'Operator-Plastics Process Mach',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper/Mineral/Metal Proces',
    value: 'Mach Oper/Mineral/Metal Proces',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Foundry Worker',
    value: 'Foundry Worker',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Rubber Process Mach',
    value: 'Operator-Rubber Process Mach',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Oper-Papermaker/Finish Mach',
    value: 'Oper-Papermaker/Finish Mach',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Aircraft Assembler',
    value: 'Inspector-Aircraft Assembler',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspc-Mot Veh & Mach Rep Assem',
    value: 'Inspc-Mot Veh & Mach Rep Assem',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Electros Assembler/Fabricator',
    value: 'Electros Assembler/Fabricator',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-ElecAppliance Manuf',
    value: 'Inspector-ElecAppliance Manuf',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Industrial Elec Motors Assem',
    value: 'Industrial Elec Motors Assem',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Mechanic Assembler',
    value: 'Inspector-Mechanic Assembler',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Other-Paper Converting Mach',
    value: 'Other-Paper Converting Mach',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper/Elec Apparatus',
    value: 'Mach Oper/Elec Apparatus',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Other Assemblers',
    value: 'Inspector-Other Assemblers',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Machining Tool',
    value: 'Operator-Machining Tool',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Boat Assembler',
    value: 'Inspector-Boat Assembler',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Other Wood Products Assembler',
    value: 'Other Wood Products Assembler',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Furniture Finisher/Refinisher',
    value: 'Furniture Finisher/Refinisher',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Plastic Prod Assemble/Finish',
    value: 'Plastic Prod Assemble/Finish',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Painter/Coater-Industrial',
    value: 'Painter/Coater-Industrial',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Plating/Metal Spraying',
    value: 'Plating/Metal Spraying',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Forging Machine',
    value: 'Operator-Forging Machine',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Metalworking Machine',
    value: 'Operator-Metalworking Machine',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper-Other Metal Products',
    value: 'Mach Oper-Other Metal Products',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper-Other Product',
    value: 'Mach Oper-Other Product',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourer-Mineral/Metal Proces',
    value: 'Labourer-Mineral/Metal Proces',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourer-Metal Fabrication',
    value: 'Labourer-Metal Fabrication',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourer-Rubber/Plastic Prod',
    value: 'Labourer-Rubber/Plastic Prod',
  },
  {
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourer-Other Process/Manu',
    value: 'Labourer-Other Process/Manu',
  },
  {
    category: 'Office & Admin',
    name: 'Mgr-Human Resources',
    value: 'Mgr-Human Resources',
  },
  {
    category: 'Office & Admin',
    name: 'Mgr-Other Admin Service',
    value: 'Mgr-Other Admin Service',
  },
  {
    category: 'Office & Admin',
    name: 'Mgr-Other Public Admin',
    value: 'Mgr-Other Public Admin',
  },
  {
    category: 'Office & Admin',
    name: 'Specialist-Human Resources',
    value: 'Specialist-Human Resources',
  },
  {
    category: 'Office & Admin',
    name: 'Supervisor-General Office',
    value: 'Supervisor-General Office',
  },
  {
    category: 'Office & Admin',
    name: 'Officer-Administration',
    value: 'Officer-Administration',
  },
  {
    category: 'Office & Admin',
    name: 'Assistant-Executive',
    value: 'Assistant-Executive',
  },
  {
    category: 'Office & Admin',
    name: 'Officer-Personnel/Recruitment',
    value: 'Officer-Personnel/Recruitment',
  },
  {
    category: 'Office & Admin',
    name: 'Secretary (exc Legal/Med)',
    value: 'Secretary (exc Legal/Med)',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-General Office',
    value: 'Clerk-General Office',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Records Mgmt/Filing',
    value: 'Clerk-Records Mgmt/Filing',
  },
  {
    category: 'Office & Admin',
    name: 'Receptionist/Switchboard Oper',
    value: 'Receptionist/Switchboard Oper',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Data Entry',
    value: 'Clerk-Data Entry',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Accounting/Related',
    value: 'Clerk-Accounting/Related',
  },
  { category: 'Office & Admin', name: 'Clerk-Payroll', value: 'Clerk-Payroll' },
  {
    category: 'Office & Admin',
    name: 'Clerk-Administrative',
    value: 'Clerk-Administrative',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Personnel',
    value: 'Clerk-Personnel',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Correspond/Publication',
    value: 'Clerk-Correspond/Publication',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Customer Service/Inform',
    value: 'Clerk-Customer Service/Inform',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Survey Interview/Stat',
    value: 'Clerk-Survey Interview/Stat',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Production',
    value: 'Clerk-Production',
  },
  {
    category: 'Office & Admin',
    name: 'Clerk-Purchasing/Inventory',
    value: 'Clerk-Purchasing/Inventory',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Engineer-Geological',
    value: 'Engineer-Geological',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Engineer-Petroleum',
    value: 'Engineer-Petroleum',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Technician-Geo/Mineral',
    value: 'Technician-Geo/Mineral',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Technician-Mapping/Related',
    value: 'Technician-Mapping/Related',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Water Well Driller',
    value: 'Water Well Driller',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Mgr-Oil/Gas/NatResGas Drl/Svc',
    value: 'Mgr-Oil/Gas/NatResGas Drl/Svc',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Oil/Gas/NatResGas Well Drl Wk',
    value: 'Oil/Gas/NatResGas Well Drl Wk',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Oil/Gas/Nat Res Gas Drill/Svc',
    value: 'Oil/Gas/Nat Res Gas Drill/Svc',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Mgr-Petro/Gas/Chemical Process',
    value: 'Mgr-Petro/Gas/Chemical Process',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Operator-Petroleum/Gas/Chem',
    value: 'Operator-Petroleum/Gas/Chem',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Operator-Chemical Plant Mach',
    value: 'Operator-Chemical Plant Mach',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Bus Owner-Oil/Gas',
    value: 'Bus Owner-Oil/Gas',
  },
  {
    category: 'Oil/Gas/Natural Resources',
    name: 'Consultant-Oil/Gas/Nat Res',
    value: 'Consultant-Oil/Gas/Nat Res',
  },
  {
    category: 'Protective Services',
    name: 'Mgr-Social Comm/Correctional',
    value: 'Mgr-Social Comm/Correctional',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Commissioned Police',
    value: 'Officer-Commissioned Police',
  },
  {
    category: 'Protective Services',
    name: 'Fire Chief/Sr Firefighter',
    value: 'Fire Chief/Sr Firefighter',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Court/Justice Peace',
    value: 'Officer-Court/Justice Peace',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Immigration/EI/Reven',
    value: 'Officer-Immigration/EI/Reven',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Prog Unique to Govt',
    value: 'Officer-Prog Unique to Govt',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Police',
    value: 'Officer-Police',
  },
  {
    category: 'Protective Services',
    name: 'Firefighter',
    value: 'Firefighter',
  },
  {
    category: 'Protective Services',
    name: 'Sheriff/Bailiff',
    value: 'Sheriff/Bailiff',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Correctional Service',
    value: 'Officer-Correctional Service',
  },
  {
    category: 'Protective Services',
    name: 'Officer-By-Law Enforce/Other',
    value: 'Officer-By-Law Enforce/Other',
  },
  {
    category: 'Protective Services',
    name: 'Armed Forces-Unique Occup',
    value: 'Armed Forces-Unique Occup',
  },
  {
    category: 'Protective Services',
    name: 'Officer-Other Protective',
    value: 'Officer-Other Protective',
  },
  {
    category: 'Protective Services',
    name: 'Operator-Dispatcher/Radio',
    value: 'Operator-Dispatcher/Radio',
  },
  {
    category: 'Protective Services',
    name: 'Guard-Security/Related Occup',
    value: 'Guard-Security/Related Occup',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Mgr-Ins Real Estate Fin Broker',
    value: 'Mgr-Ins Real Estate Fin Broker',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Administrator-Property',
    value: 'Administrator-Property',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Insurance Adjuster/Claims',
    value: 'Insurance Adjuster/Claims',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Assessor/Valuator/Appraiser',
    value: 'Assessor/Valuator/Appraiser',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Land Surveyor',
    value: 'Land Surveyor',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Technician-Land Survey',
    value: 'Technician-Land Survey',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Agent-Insurance/Broker',
    value: 'Agent-Insurance/Broker',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Agent-Real Estate/Salesperson',
    value: 'Agent-Real Estate/Salesperson',
  },
  {
    category: 'Real Estate, Insurance & Related Services',
    name: 'Bus Owner-Real Est/Insurance',
    value: 'Bus Owner-Real Est/Insurance',
  },
  {
    category: 'Sales & Service',
    name: 'Mgr-Purchasing',
    value: 'Mgr-Purchasing',
  },
  {
    category: 'Sales & Service',
    name: 'Mgr-Sales/Mrkt/Adver',
    value: 'Mgr-Sales/Mrkt/Adver',
  },
  {
    category: 'Sales & Service',
    name: 'Mgr-Retail Trade',
    value: 'Mgr-Retail Trade',
  },
  {
    category: 'Sales & Service',
    name: 'Mgr-Accommodation Service',
    value: 'Mgr-Accommodation Service',
  },
  {
    category: 'Sales & Service',
    name: 'Officer-Purchasing Agent',
    value: 'Officer-Purchasing Agent',
  },
  {
    category: 'Sales & Service',
    name: 'Representative-CustomerService',
    value: 'Representative-CustomerService',
  },
  { category: 'Sales & Service', name: 'Cashier', value: 'Cashier' },
  {
    category: 'Sales & Service',
    name: 'Clerk-Storekeeper/Parts',
    value: 'Clerk-Storekeeper/Parts',
  },
  {
    category: 'Sales & Service',
    name: 'Technical Sales Specialist',
    value: 'Technical Sales Specialist',
  },
  {
    category: 'Sales & Service',
    name: 'Buyer Retail/Wholesale',
    value: 'Buyer Retail/Wholesale',
  },
  {
    category: 'Sales & Service',
    name: 'Retail Salesperson/Sales Clerk',
    value: 'Retail Salesperson/Sales Clerk',
  },
  {
    category: 'Sales & Service',
    name: 'Clerk-Hotel Front Desk',
    value: 'Clerk-Hotel Front Desk',
  },
  {
    category: 'Sales & Service',
    name: 'Attendant-Service Station',
    value: 'Attendant-Service Station',
  },
  {
    category: 'Sales & Service',
    name: 'Shoe Repairer/Shoemaker',
    value: 'Shoe Repairer/Shoemaker',
  },
  {
    category: 'Sales & Service',
    name: 'Mgr-Furniture/Fixtures',
    value: 'Mgr-Furniture/Fixtures',
  },
  {
    category: 'Sales & Service',
    name: 'Business Owner-Retail',
    value: 'Business Owner-Retail',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Physicist/Astronomer',
    value: 'Physicist/Astronomer',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Chemist',
    value: 'Chemist',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Geologist/Geochemist',
    value: 'Geologist/Geochemist',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Meteorologist',
    value: 'Meteorologist',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Biologist/Related Scientist',
    value: 'Biologist/Related Scientist',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Technician-Chemical',
    value: 'Technician-Chemical',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Technician-Meteorological',
    value: 'Technician-Meteorological',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Technician-Biological',
    value: 'Technician-Biological',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Consultant-Natural/Applied Sci',
    value: 'Consultant-Natural/Applied Sci',
  },
  {
    category: 'Science & Scientific Research',
    name: 'Technician-Environmental',
    value: 'Technician-Environmental',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Director-Rec Sports/Services',
    value: 'Director-Rec Sports/Services',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Sports/Recreation/Fitness Prog',
    value: 'Sports/Recreation/Fitness Prog',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Athlete',
    value: 'Athlete',
  },
  { category: 'Sports, Fitness & Recreation', name: 'Coach', value: 'Coach' },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Official-Sports/Referee',
    value: 'Official-Sports/Referee',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Instructor Rec/Sports/Fitness',
    value: 'Instructor Rec/Sports/Fitness',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Guide-OutdoorSport/Recreation',
    value: 'Guide-OutdoorSport/Recreation',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Oper-Amusement/Rec/Sport',
    value: 'Oper-Amusement/Rec/Sport',
  },
  {
    category: 'Sports, Fitness & Recreation',
    name: 'Bus Owner-Fitness & Rec',
    value: 'Bus Owner-Fitness & Rec',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Patternmaker-Textile/Leather',
    value: 'Patternmaker-Textile/Leather',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Textile Machine Mech/Repair',
    value: 'Textile Machine Mech/Repair',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Upholsterer',
    value: 'Upholsterer',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Tailor/Dressmaker/Furrier',
    value: 'Tailor/Dressmaker/Furrier',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Mgr-Textile Processing',
    value: 'Mgr-Textile Processing',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Mgr-Fabric/Fur/Leather',
    value: 'Mgr-Fabric/Fur/Leather',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Oper-Textile Fibre/Yarn Prep',
    value: 'Oper-Textile Fibre/Yarn Prep',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Weaver/Knitter/Other Fabric',
    value: 'Weaver/Knitter/Other Fabric',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Oper-Textile Dyeing/Finishing',
    value: 'Oper-Textile Dyeing/Finishing',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Textile /Grader/Sampler',
    value: 'Textile /Grader/Sampler',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Operator-Sewing Machine',
    value: 'Operator-Sewing Machine',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Fabric/Fur/Leather Cutter',
    value: 'Fabric/Fur/Leather Cutter',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Hide/Pelt Processing Worker',
    value: 'Hide/Pelt Processing Worker',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Tester/Fabric/Fur/Leather',
    value: 'Tester/Fabric/Fur/Leather',
  },
  {
    category: 'Textiles & Textile Related',
    name: 'Labourer-Textile Processing',
    value: 'Labourer-Textile Processing',
  },
  {
    category: 'Travel & Transportation',
    name: 'Mgr-Transportation',
    value: 'Mgr-Transportation',
  },
  {
    category: 'Travel & Transportation',
    name: 'Customs/Ship/Other Broker',
    value: 'Customs/Ship/Other Broker',
  },
  {
    category: 'Travel & Transportation',
    name: 'Trans Route/Crew Scheduler',
    value: 'Trans Route/Crew Scheduler',
  },
  {
    category: 'Travel & Transportation',
    name: 'Technician-Air Instrum/Avion',
    value: 'Technician-Air Instrum/Avion',
  },
  {
    category: 'Travel & Transportation',
    name: 'Air Traffic Control/Related',
    value: 'Air Traffic Control/Related',
  },
  {
    category: 'Travel & Transportation',
    name: 'Officer-Deck/Water Transport',
    value: 'Officer-Deck/Water Transport',
  },
  {
    category: 'Travel & Transportation',
    name: 'Railway/Marine Traffic Contr',
    value: 'Railway/Marine Traffic Contr',
  },
  {
    category: 'Travel & Transportation',
    name: 'Counsellor-Travel',
    value: 'Counsellor-Travel',
  },
  {
    category: 'Travel & Transportation',
    name: 'Attendant-Purser/Flight',
    value: 'Attendant-Purser/Flight',
  },
  {
    category: 'Travel & Transportation',
    name: 'Agent-Airline Sales/Service',
    value: 'Agent-Airline Sales/Service',
  },
  {
    category: 'Travel & Transportation',
    name: 'Agent-Ticket/Cargo Svc Rep',
    value: 'Agent-Ticket/Cargo Svc Rep',
  },
  {
    category: 'Travel & Transportation',
    name: 'Guide-Tour/Travel',
    value: 'Guide-Tour/Travel',
  },
  {
    category: 'Travel & Transportation',
    name: 'Attendant-Accomm/Travel',
    value: 'Attendant-Accomm/Travel',
  },
  {
    category: 'Travel & Transportation',
    name: 'Mgr-Railway Transport Oper',
    value: 'Mgr-Railway Transport Oper',
  },
  {
    category: 'Travel & Transportation',
    name: 'Mgr-Motor/Ground Transit Oper',
    value: 'Mgr-Motor/Ground Transit Oper',
  },
  {
    category: 'Travel & Transportation',
    name: 'Railway Carman/Woman',
    value: 'Railway Carman/Woman',
  },
  {
    category: 'Travel & Transportation',
    name: 'Aircraft Mech/ Inspector',
    value: 'Aircraft Mech/ Inspector',
  },
  {
    category: 'Travel & Transportation',
    name: 'Engineer-Railway/Yard Train',
    value: 'Engineer-Railway/Yard Train',
  },
  {
    category: 'Travel & Transportation',
    name: 'Rail Conductor/Brakeman',
    value: 'Rail Conductor/Brakeman',
  },
  {
    category: 'Travel & Transportation',
    name: 'Bus/Subway/Other Transit',
    value: 'Bus/Subway/Other Transit',
  },
  {
    category: 'Travel & Transportation',
    name: 'Taxi/Limo Driver/Chauffeur',
    value: 'Taxi/Limo Driver/Chauffeur',
  },
  {
    category: 'Travel & Transportation',
    name: 'Railway Yard Worker',
    value: 'Railway Yard Worker',
  },
  {
    category: 'Travel & Transportation',
    name: 'Railway Track Mtce Worker',
    value: 'Railway Track Mtce Worker',
  },
  {
    category: 'Travel & Transportation',
    name: 'Deck Crew/Water Transport',
    value: 'Deck Crew/Water Transport',
  },
  {
    category: 'Travel & Transportation',
    name: 'Engine Rm Crew/Water Trans',
    value: 'Engine Rm Crew/Water Trans',
  },
  {
    category: 'Travel & Transportation',
    name: 'Operator-Lock/Cable Ferry',
    value: 'Operator-Lock/Cable Ferry',
  },
  {
    category: 'Travel & Transportation',
    name: 'Operator-Boat',
    value: 'Operator-Boat',
  },
  {
    category: 'Travel & Transportation',
    name: 'Attendant-Air Transp Ramp',
    value: 'Attendant-Air Transp Ramp',
  },
  {
    category: 'Travel & Transportation',
    name: 'Railway/Motor Transp Labour',
    value: 'Railway/Motor Transp Labour',
  },
  {
    category: 'Travel & Transportation',
    name: 'Bus Owner-Transport',
    value: 'Bus Owner-Transport',
  },
  {
    category: 'Utilities',
    name: 'Mgr-TeleComm. Carriers',
    value: 'Mgr-TeleComm. Carriers',
  },
  { category: 'Utilities', name: 'Mgr-Utilities', value: 'Mgr-Utilities' },
  {
    category: 'Utilities',
    name: 'Operator-Telephone',
    value: 'Operator-Telephone',
  },
  {
    category: 'Utilities',
    name: 'Elec Power Line/Cable Worker',
    value: 'Elec Power Line/Cable Worker',
  },
  {
    category: 'Utilities',
    name: 'Telecomm Line/Cable Worker',
    value: 'Telecomm Line/Cable Worker',
  },
  {
    category: 'Utilities',
    name: 'TeleComm Install/Repair Worker',
    value: 'TeleComm Install/Repair Worker',
  },
  {
    category: 'Utilities',
    name: 'Cable Television Svc/Mtce Tech',
    value: 'Cable Television Svc/Mtce Tech',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Contractor-Mgr/Mechanic',
    value: 'Contractor-Mgr/Mechanic',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Heavy-Duty Equip Mech',
    value: 'Heavy-Duty Equip Mech',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Auto Truck Bus',
    value: 'Mechanic-Auto Truck Bus',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Motor Veh Mach&Body Rep',
    value: 'Motor Veh Mach&Body Rep',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Elec  Appliance Svc/Repair',
    value: 'Elec  Appliance Svc/Repair',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Electrical',
    value: 'Mechanic-Electrical',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Motorcycle/Other',
    value: 'Mechanic-Motorcycle/Other',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Small Engine/Equip',
    value: 'Mechanic-Small Engine/Equip',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Auto Mech Installer/Servicer',
    value: 'Auto Mech Installer/Servicer',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Other Repairer/Servicer',
    value: 'Other Repairer/Servicer',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Bus Owner-Vehicle Repair',
    value: 'Bus Owner-Vehicle Repair',
  },
  {
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Bus Owner-Machine Repair',
    value: 'Bus Owner-Machine Repair',
  },
];
