export default [
  {
    // id: 2123,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Consultant-Agricultural Reps',
    value: 'Consultant-Agricultural Reps',
  },
  {
    // id: 2222,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Inspector-Agri/Fish Products',
    value: 'Inspector-Agri/Fish Products',
  },
  {
    // id: 2225,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Specialists-Landscape/Horticul',
    value: 'Specialists-Landscape/Horticul',
  },
  {
    // id: 6234,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Operator-Grain Elevator',
    value: 'Operator-Grain Elevator',
  },
  {
    // id: 8251,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Farmers/Farm Manager',
    value: 'Farmers/Farm Manager',
  },
  {
    // id: 8252,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Agricultural/Related Service',
    value: 'Agricultural/Related Service',
  },
  {
    // id: 8253,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Farm Mgr/Livestock Workers',
    value: 'Farm Mgr/Livestock Workers',
  },
  {
    // id: 8254,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Operator-Nursery/Greenhouse',
    value: 'Operator-Nursery/Greenhouse',
  },
  {
    // id: 8255,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Landscaping/Grounds Mtce',
    value: 'Landscaping/Grounds Mtce',
  },
  {
    // id: 8256,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Mgr-Landscape/Horticulture',
    value: 'Mgr-Landscape/Horticulture',
  },
  {
    // id: 8257,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Mgr-Aquaculture Operator',
    value: 'Mgr-Aquaculture Operator',
  },
  {
    // id: 8431,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'General Farm Workers',
    value: 'General Farm Workers',
  },
  {
    // id: 8432,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Nursery/Greenhouse Workers',
    value: 'Nursery/Greenhouse Workers',
  },
  {
    // id: 8611,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Harvesting Labourers',
    value: 'Harvesting Labourers',
  },
  {
    // id: 8613,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Aquaculture/Marine Harvest',
    value: 'Aquaculture/Marine Harvest',
  },
  {
    // id: 9909,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Bee Keeper/Apiary Farmer',
    value: 'Bee Keeper/Apiary Farmer',
  },
  {
    // id: 9914,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Grain Farmer',
    value: 'Grain Farmer',
  },
  {
    // id: 9915,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Mixed Farmer',
    value: 'Mixed Farmer',
  },
  {
    // id: 9916,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Rancher',
    value: 'Rancher',
  },
  {
    // id: 9918,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Bus Owner - Ag Related',
    value: 'Bus Owner - Ag Related',
  },
  {
    // id: 9919,
    category: 'Agriculture, Aquaculture & Horticulture',
    name: 'Bus Owner - Landscape/Grounds',
    value: 'Bus Owner - Landscape/Grounds',
  },

  {
    // id: 211,
    category: 'Architecture & Engineering',
    name: 'Mgr-Engineering',
    value: 'Mgr-Engineering',
  },
  {
    // id: 212,
    category: 'Architecture & Engineering',
    name: 'Mgr-Architecture/Science',
    value: 'Mgr-Architecture/Science',
  },
  {
    // id: 2131,
    category: 'Architecture & Engineering',
    name: 'Engineer-Civil',
    value: 'Engineer-Civil',
  },
  {
    // id: 2132,
    category: 'Architecture & Engineering',
    name: 'Engineer-Mechanical',
    value: 'Engineer-Mechanical',
  },
  {
    // id: 2133,
    category: 'Architecture & Engineering',
    name: 'Engineer-Electrical',
    value: 'Engineer-Electrical',
  },
  {
    // id: 2134,
    category: 'Architecture & Engineering',
    name: 'Engineer-Chemical',
    value: 'Engineer-Chemical',
  },
  {
    // id: 2141,
    category: 'Architecture & Engineering',
    name: 'Engineer-Industrial/Manuf',
    value: 'Engineer-Industrial/Manuf',
  },
  {
    // id: 2142,
    category: 'Architecture & Engineering',
    name: 'Engineer-Meta/Materials',
    value: 'Engineer-Meta/Materials',
  },
  {
    // id: 2146,
    category: 'Architecture & Engineering',
    name: 'Engineer-Aerospace',
    value: 'Engineer-Aerospace',
  },
  {
    // id: 2148,
    category: 'Architecture & Engineering',
    name: 'Engineer-Other',
    value: 'Engineer-Other',
  },
  {
    // id: 2151,
    category: 'Architecture & Engineering',
    name: 'Architects',
    value: 'Architects',
  },
  {
    // id: 2152,
    category: 'Architecture & Engineering',
    name: 'Architects-Landscape',
    value: 'Architects-Landscape',
  },
  {
    // id: 2153,
    category: 'Architecture & Engineering',
    name: 'Urban/Use Planners',
    value: 'Urban/Use Planners',
  },
  {
    // id: 2231,
    category: 'Architecture & Engineering',
    name: 'Technician-Civil Engineering',
    value: 'Technician-Civil Engineering',
  },
  {
    // id: 2232,
    category: 'Architecture & Engineering',
    name: 'Technician-Mech Engineering',
    value: 'Technician-Mech Engineering',
  },
  {
    // id: 2233,
    category: 'Architecture & Engineering',
    name: 'Technician-Indus Engineering',
    value: 'Technician-Indus Engineering',
  },
  {
    // id: 2241,
    category: 'Architecture & Engineering',
    name: 'Technician-Electrical Engineer',
    value: 'Technician-Electrical Engineer',
  },
  {
    // id: 2243,
    category: 'Architecture & Engineering',
    name: 'Technician-Industrial Instrum',
    value: 'Technician-Industrial Instrum',
  },
  {
    // id: 2251,
    category: 'Architecture & Engineering',
    name: 'Technician-Architectural',
    value: 'Technician-Architectural',
  },
  {
    // id: 2252,
    category: 'Architecture & Engineering',
    name: 'Designer-Industrial',
    value: 'Designer-Industrial',
  },
  {
    // id: 2253,
    category: 'Architecture & Engineering',
    name: 'Technician-Drafting',
    value: 'Technician-Drafting',
  },
  {
    // id: 2261,
    category: 'Architecture & Engineering',
    name: 'Inspec-Non-Destructive Testers',
    value: 'Inspec-Non-Destructive Testers',
  },
  {
    // id: 2262,
    category: 'Architecture & Engineering',
    name: 'Inspector-Engineering/Regulatr',
    value: 'Inspector-Engineering/Regulatr',
  },
  {
    // id: 2274,
    category: 'Architecture & Engineering',
    name: 'Officer-Engineer/Water Trans',
    value: 'Officer-Engineer/Water Trans',
  },
  {
    // id: 9920,
    category: 'Architecture & Engineering',
    name: 'Bus Owner - Architecture',
    value: 'Bus Owner - Architecture',
  },

  {
    // id: 512,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Mgr-Broadcasting/Perform Arts',
    value: 'Mgr-Broadcasting/Perform Arts',
  },
  {
    // id: 1226,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Conference/Event Planners',
    value: 'Conference/Event Planners',
  },
  {
    // id: 1423,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Desktop Publish Oper/Related',
    value: 'Desktop Publish Oper/Related',
  },
  {
    // id: 1435,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Art Collectors',
    value: 'Art Collectors',
  },
  {
    // id: 5112,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Conservators/Curators',
    value: 'Conservators/Curators',
  },
  {
    // id: 5121,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Authors/Writers',
    value: 'Authors/Writers',
  },
  {
    // id: 5122,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Editors',
    value: 'Editors',
  },
  {
    // id: 5123,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Journalists',
    value: 'Journalists',
  },
  {
    // id: 5124,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Public Relations/Communication',
    value: 'Public Relations/Communication',
  },
  {
    // id: 5131,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Producers/Directors/Choreograp',
    value: 'Producers/Directors/Choreograp',
  },
  {
    // id: 5132,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Conductors/Composers',
    value: 'Conductors/Composers',
  },
  {
    // id: 5133,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Musicians/Singers',
    value: 'Musicians/Singers',
  },
  {
    // id: 5134,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Dancers/Performers',
    value: 'Dancers/Performers',
  },
  {
    // id: 5135,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Actors/Comedians',
    value: 'Actors/Comedians',
  },
  {
    // id: 5136,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Painters/Sculptors/Other',
    value: 'Painters/Sculptors/Other',
  },
  {
    // id: 5212,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Museum/Art Gallery worker',
    value: 'Museum/Art Gallery worker',
  },
  {
    // id: 5221,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Photographers',
    value: 'Photographers',
  },
  {
    // id: 5222,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Operator-Film/Video Camera',
    value: 'Operator-Film/Video Camera',
  },
  {
    // id: 5223,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Technician-Graphic Arts',
    value: 'Technician-Graphic Arts',
  },
  {
    // id: 5224,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Technician-Broadcast',
    value: 'Technician-Broadcast',
  },
  {
    // id: 5225,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Technician-Audio/Video Record',
    value: 'Technician-Audio/Video Record',
  },
  {
    // id: 5226,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Motion Pic/Broadcast/Perf Arts',
    value: 'Motion Pic/Broadcast/Perf Arts',
  },
  {
    // id: 5227,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Mgr Motion Pic/Broad/Perf Arts',
    value: 'Mgr Motion Pic/Broad/Perf Arts',
  },
  {
    // id: 5231,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Announcers/Other Broadcasters',
    value: 'Announcers/Other Broadcasters',
  },
  {
    // id: 5232,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Performers-Other',
    value: 'Performers-Other',
  },
  {
    // id: 5241,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Designer-Graphic/Illustrators',
    value: 'Designer-Graphic/Illustrators',
  },
  {
    // id: 5242,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Designer-Interior',
    value: 'Designer-Interior',
  },
  {
    // id: 5243,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Designer-Theatre/Fashion',
    value: 'Designer-Theatre/Fashion',
  },
  {
    // id: 5244,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Artisans/Craftspersons',
    value: 'Artisans/Craftspersons',
  },
  {
    // id: 6443,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Attendant-Casino',
    value: 'Attendant-Casino',
  },
  {
    // id: 6481,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Consult-Image/Social/Other',
    value: 'Consult-Image/Social/Other',
  },
  {
    // id: 7218,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Mgr-Printing/Related',
    value: 'Mgr-Printing/Related',
  },
  {
    // id: 7381,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Operator-Printing Press',
    value: 'Operator-Printing Press',
  },
  {
    // id: 9471,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Operator-Printing Machine',
    value: 'Operator-Printing Machine',
  },
  {
    // id: 9472,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Camera/Platemaking Prepress',
    value: 'Camera/Platemaking Prepress',
  },
  {
    // id: 9474,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Photographic/Film Processors',
    value: 'Photographic/Film Processors',
  },
  {
    // id: 9921,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Bus Owner - Media',
    value: 'Bus Owner - Media',
  },
  {
    // id: 9922,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Bus Owner - Arts & Design',
    value: 'Bus Owner - Arts & Design',
  },
  {
    // id: 9923,
    category: 'Arts, Design, Entertainment & Media',
    name: 'Bus Owner - Entertainment',
    value: 'Bus Owner - Entertainment',
  },

  {
    // id: 111,
    category: 'Business & Financial',
    name: 'Mgr-Financial',
    value: 'Mgr-Financial',
  },
  {
    // id: 122,
    category: 'Business & Financial',
    name: 'Mgr-Banking/Credit',
    value: 'Mgr-Banking/Credit',
  },
  {
    // id: 123,
    category: 'Business & Financial',
    name: 'Mgr-Other Bus. Service',
    value: 'Mgr-Other Bus. Service',
  },
  {
    // id: 1111,
    category: 'Business & Financial',
    name: 'Fin-Auditors/Accountants',
    value: 'Fin-Auditors/Accountants',
  },
  {
    // id: 1112,
    category: 'Business & Financial',
    name: 'Fin-Investment Analysts',
    value: 'Fin-Investment Analysts',
  },
  {
    // id: 1113,
    category: 'Business & Financial',
    name: 'Fin-Investment Dealers/Brokers',
    value: 'Fin-Investment Dealers/Brokers',
  },
  {
    // id: 1114,
    category: 'Business & Financial',
    name: 'Officer-Other Financial',
    value: 'Officer-Other Financial',
  },
  {
    // id: 1212,
    category: 'Business & Financial',
    name: 'Supervisors-Finance Insurance',
    value: 'Supervisors-Finance Insurance',
  },
  {
    // id: 1215,
    category: 'Business & Financial',
    name: 'Supervisors-Record/Dist/Sched',
    value: 'Supervisors-Record/Dist/Sched',
  },
  {
    // id: 1231,
    category: 'Business & Financial',
    name: 'Bookkeepers',
    value: 'Bookkeepers',
  },
  {
    // id: 1232,
    category: 'Business & Financial',
    name: 'Loans/credit officers',
    value: 'Loans/credit officers',
  },
  {
    // id: 1234,
    category: 'Business & Financial',
    name: 'Insurance Underwriters',
    value: 'Insurance Underwriters',
  },
  {
    // id: 1434,
    category: 'Business & Financial',
    name: 'Clerk-Banking/Ins/Other Financ',
    value: 'Clerk-Banking/Ins/Other Financ',
  },
  {
    // id: 1434,
    category: 'Business & Financial',
    name: 'Branch sales/Call Centre agent',
    value: 'Branch sales/Call Centre agent',
  },
  {
    // id: 2161,
    category: 'Business & Financial',
    name: 'Math/Statisticians/Actuaries',
    value: 'Math/Statisticians/Actuaries',
  },
  {
    // id: 4162,
    category: 'Business & Financial',
    name: 'Analyst-Econ Policy Research',
    value: 'Analyst-Econ Policy Research',
  },
  {
    // id: 4163,
    category: 'Business & Financial',
    name: 'Consultant-Bus. Dev /Marketing',
    value: 'Consultant-Bus. Dev /Marketing',
  },
  {
    // id: 4164,
    category: 'Business & Financial',
    name: 'Consult-Social Policy Research',
    value: 'Consult-Social Policy Research',
  },
  {
    // id: 9924,
    category: 'Business & Financial',
    name: 'Bus Owner - Financial',
    value: 'Bus Owner - Financial',
  },

  {
    // id: 6271,
    category: 'Child Care & Personal Services',
    name: 'Hairstylists/Barbers',
    value: 'Hairstylists/Barbers',
  },
  {
    // id: 6474,
    category: 'Child Care & Personal Services',
    name: 'Babysitters/Nannies',
    value: 'Babysitters/Nannies',
  },
  {
    // id: 6482,
    category: 'Child Care & Personal Services',
    name: 'Estheticians/Electrologists',
    value: 'Estheticians/Electrologists',
  },
  {
    // id: 6483,
    category: 'Child Care & Personal Services',
    name: 'Pet Groomers/Animal Care',
    value: 'Pet Groomers/Animal Care',
  },
  {
    // id: 6484,
    category: 'Child Care & Personal Services',
    name: 'Other Personal Service',
    value: 'Other Personal Service',
  },
  {
    // id: 7344,
    category: 'Child Care & Personal Services',
    name: 'Jewellers/Watch Repairers',
    value: 'Jewellers/Watch Repairers',
  },
  {
    // id: 9906,
    category: 'Child Care & Personal Services',
    name: 'Stay at home parent',
    value: 'Stay at home parent',
  },
  {
    // id: 9908,
    category: 'Child Care & Personal Services',
    name: 'Child Care Provider/Youth Work',
    value: 'Child Care Provider/Youth Work',
  },
  {
    // id: 9925,
    category: 'Child Care & Personal Services',
    name: 'Bus Owner - Esthetics',
    value: 'Bus Owner - Esthetics',
  },
  {
    // id: 9926,
    category: 'Child Care & Personal Services',
    name: 'Bus Owner - Child Care',
    value: 'Bus Owner - Child Care',
  },

  {
    // id: 4153,
    category: 'Community/Spiritual Services',
    name: 'Counsellor-Family/Marriage',
    value: 'Counsellor-Family/Marriage',
  },
  {
    // id: 4154,
    category: 'Community/Spiritual Services',
    name: 'Ministers of Religion',
    value: 'Ministers of Religion',
  },
  {
    // id: 4212,
    category: 'Community/Spiritual Services',
    name: 'Community/Social Service wrkr',
    value: 'Community/Social Service wrkr',
  },
  {
    // id: 4213,
    category: 'Community/Spiritual Services',
    name: 'Counsellors-Employment',
    value: 'Counsellors-Employment',
  },
  {
    // id: 4217,
    category: 'Community/Spiritual Services',
    name: 'Religious-Other',
    value: 'Religious-Other',
  },
  {
    // id: 6272,
    category: 'Community/Spiritual Services',
    name: 'Funeral Directors/Embalmers',
    value: 'Funeral Directors/Embalmers',
  },

  {
    // id: 213,
    category: 'Computer Technology & Other Computer Related',
    name: 'Mgr-Computer/Info Sys',
    value: 'Mgr-Computer/Info Sys',
  },
  {
    // id: 2147,
    category: 'Computer Technology & Other Computer Related',
    name: 'Engineer-Computer',
    value: 'Engineer-Computer',
  },
  {
    // id: 2171,
    category: 'Computer Technology & Other Computer Related',
    name: 'Consultant-Information Systems',
    value: 'Consultant-Information Systems',
  },
  {
    // id: 2172,
    category: 'Computer Technology & Other Computer Related',
    name: 'Analyst-Database/Data Admin',
    value: 'Analyst-Database/Data Admin',
  },
  {
    // id: 2173,
    category: 'Computer Technology & Other Computer Related',
    name: 'Engineer-Software Designer',
    value: 'Engineer-Software Designer',
  },
  {
    // id: 2174,
    category: 'Computer Technology & Other Computer Related',
    name: 'Computer Program/Interactive',
    value: 'Computer Program/Interactive',
  },
  {
    // id: 2175,
    category: 'Computer Technology & Other Computer Related',
    name: 'Designer-Web Developers',
    value: 'Designer-Web Developers',
  },
  {
    // id: 2242,
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-Electronic Service',
    value: 'Technician-Electronic Service',
  },
  {
    // id: 2281,
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-Computer Network',
    value: 'Technician-Computer Network',
  },
  {
    // id: 2282,
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-User Support',
    value: 'Technician-User Support',
  },
  {
    // id: 2283,
    category: 'Computer Technology & Other Computer Related',
    name: 'Technician-Systems Testing',
    value: 'Technician-Systems Testing',
  },
  {
    // id: 9927,
    category: 'Computer Technology & Other Computer Related',
    name: 'Bus Owner - Computer Related',
    value: 'Bus Owner - Computer Related',
  },

  {
    // id: 711,
    category: 'Construction & Construction Trades',
    name: 'Mgr-Construction',
    value: 'Mgr-Construction',
  },
  {
    // id: 712,
    category: 'Construction & Construction Trades',
    name: 'Residential Home Builder/Reno',
    value: 'Residential Home Builder/Reno',
  },
  {
    // id: 2234,
    category: 'Construction & Construction Trades',
    name: 'Construction Estimators',
    value: 'Construction Estimators',
  },
  {
    // id: 2264,
    category: 'Construction & Construction Trades',
    name: 'Inspector-Construction',
    value: 'Inspector-Construction',
  },
  {
    // id: 7212,
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Elec Trades',
    value: 'Contractor-Mgr/Elec Trades',
  },
  {
    // id: 7213,
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Pipefitting',
    value: 'Contractor-Mgr/Pipefitting',
  },
  {
    // id: 7215,
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Carpentry',
    value: 'Contractor-Mgr/Carpentry',
  },
  {
    // id: 7217,
    category: 'Construction & Construction Trades',
    name: 'Contractors/Mgr/Heavy Const',
    value: 'Contractors/Mgr/Heavy Const',
  },
  {
    // id: 7219,
    category: 'Construction & Construction Trades',
    name: 'Contractor-Mgr/Other Const',
    value: 'Contractor-Mgr/Other Const',
  },
  {
    // id: 7241,
    category: 'Construction & Construction Trades',
    name: 'Electrician',
    value: 'Electrician',
  },
  {
    // id: 7242,
    category: 'Construction & Construction Trades',
    name: 'Electricians-Industrial',
    value: 'Electricians-Industrial',
  },
  {
    // id: 7243,
    category: 'Construction & Construction Trades',
    name: 'Electrician-Power System',
    value: 'Electrician-Power System',
  },
  {
    // id: 7251,
    category: 'Construction & Construction Trades',
    name: 'Plumbers',
    value: 'Plumbers',
  },
  {
    // id: 7252,
    category: 'Construction & Construction Trades',
    name: 'Steam/Pipe fit /Sprinkler Inst',
    value: 'Steam/Pipe fit /Sprinkler Inst',
  },
  {
    // id: 7253,
    category: 'Construction & Construction Trades',
    name: 'Gas Fitters',
    value: 'Gas Fitters',
  },
  {
    // id: 7265,
    category: 'Construction & Construction Trades',
    name: 'Operator-Welders/Related Mach',
    value: 'Operator-Welders/Related Mach',
  },
  {
    // id: 7271,
    category: 'Construction & Construction Trades',
    name: 'Carpenters',
    value: 'Carpenters',
  },
  {
    // id: 7272,
    category: 'Construction & Construction Trades',
    name: 'Cabinetmakers',
    value: 'Cabinetmakers',
  },
  {
    // id: 7281,
    category: 'Construction & Construction Trades',
    name: 'Bricklayers',
    value: 'Bricklayers',
  },
  {
    // id: 7282,
    category: 'Construction & Construction Trades',
    name: 'Concrete Finishers',
    value: 'Concrete Finishers',
  },
  {
    // id: 7283,
    category: 'Construction & Construction Trades',
    name: 'Tilesetters',
    value: 'Tilesetters',
  },
  {
    // id: 7284,
    category: 'Construction & Construction Trades',
    name: 'Plasterers/Drywall/Finishers',
    value: 'Plasterers/Drywall/Finishers',
  },
  {
    // id: 7291,
    category: 'Construction & Construction Trades',
    name: 'Roofers/Shinglers',
    value: 'Roofers/Shinglers',
  },
  {
    // id: 7293,
    category: 'Construction & Construction Trades',
    name: 'Insulators',
    value: 'Insulators',
  },
  {
    // id: 7294,
    category: 'Construction & Construction Trades',
    name: 'Painters/Decorators',
    value: 'Painters/Decorators',
  },
  {
    // id: 7295,
    category: 'Construction & Construction Trades',
    name: 'Floor Covering Installer',
    value: 'Floor Covering Installer',
  },
  {
    // id: 7311,
    category: 'Construction & Construction Trades',
    name: 'Construct Millwrights/Industri',
    value: 'Construct Millwrights/Industri',
  },
  {
    // id: 7313,
    category: 'Construction & Construction Trades',
    name: 'Refrig/Air Conditioning mech',
    value: 'Refrig/Air Conditioning mech',
  },
  {
    // id: 7318,
    category: 'Construction & Construction Trades',
    name: 'Elevator Constructors/mech',
    value: 'Elevator Constructors/mech',
  },
  {
    // id: 7331,
    category: 'Construction & Construction Trades',
    name: 'Oil/Solid Fuel Heating mechanc',
    value: 'Oil/Solid Fuel Heating mechanc',
  },
  {
    // id: 7351,
    category: 'Construction & Construction Trades',
    name: 'Engineer-Stationary/ Operator',
    value: 'Engineer-Stationary/ Operator',
  },
  {
    // id: 7352,
    category: 'Construction & Construction Trades',
    name: 'Operator-Power Systems/Stat',
    value: 'Operator-Power Systems/Stat',
  },
  {
    // id: 7371,
    category: 'Construction & Construction Trades',
    name: 'Operator-Crane',
    value: 'Operator-Crane',
  },
  {
    // id: 7383,
    category: 'Construction & Construction Trades',
    name: 'Other Trades/Related Occup',
    value: 'Other Trades/Related Occup',
  },
  {
    // id: 7421,
    category: 'Construction & Construction Trades',
    name: 'Operator-Heavy equipment',
    value: 'Operator-Heavy equipment',
  },
  {
    // id: 7441,
    category: 'Construction & Construction Trades',
    name: 'Res/Comm Installers/Servicer',
    value: 'Res/Comm Installers/Servicer',
  },
  {
    // id: 7611,
    category: 'Construction & Construction Trades',
    name: 'Construct Trades Labourers',
    value: 'Construct Trades Labourers',
  },
  {
    // id: 7612,
    category: 'Construction & Construction Trades',
    name: 'Other Trades Helpers/Labourers',
    value: 'Other Trades Helpers/Labourers',
  },
  {
    // id: 9414,
    category: 'Construction & Construction Trades',
    name: 'Concrete/Clay/Stone Forming Op',
    value: 'Concrete/Clay/Stone Forming Op',
  },
  {
    // id: 9414,
    category: 'Construction & Construction Trades',
    name: 'Stone Masons ',
    value: 'Stone Masons ',
  },
  {
    // id: 9928,
    category: 'Construction & Construction Trades',
    name: 'Bus Owner - Construction',
    value: 'Bus Owner - Construction',
  },
  {
    // id: 9929,
    category: 'Construction & Construction Trades',
    name: 'Bus Owner - Trade',
    value: 'Bus Owner - Trade',
  },

  {
    // id: 132,
    category: 'Delivery & Postal Services',
    name: 'Mgr-Postal/Courier Service',
    value: 'Mgr-Postal/Courier Service',
  },
  {
    // id: 1214,
    category: 'Delivery & Postal Services',
    name: 'Supervisors-Mail/Distribution',
    value: 'Supervisors-Mail/Distribution',
  },
  {
    // id: 1461,
    category: 'Delivery & Postal Services',
    name: 'Clerk-Mail/Postal/Related',
    value: 'Clerk-Mail/Postal/Related',
  },
  {
    // id: 1462,
    category: 'Delivery & Postal Services',
    name: 'Letter Carriers',
    value: 'Letter Carriers',
  },
  {
    // id: 1463,
    category: 'Delivery & Postal Services',
    name: 'Courier/Door-to-Door Distrib',
    value: 'Courier/Door-to-Door Distrib',
  },
  {
    // id: 1471,
    category: 'Delivery & Postal Services',
    name: 'Shippers/Receivers',
    value: 'Shippers/Receivers',
  },
  {
    // id: 7411,
    category: 'Delivery & Postal Services',
    name: 'Truck Drivers Long/Short/Local',
    value: 'Truck Drivers Long/Short/Local',
  },
  {
    // id: 7414,
    category: 'Delivery & Postal Services',
    name: 'Delivery/Courier Svc Drivers',
    value: 'Delivery/Courier Svc Drivers',
  },
  {
    // id: 9930,
    category: 'Delivery & Postal Services',
    name: 'Bus Owner - Delivery Services',
    value: 'Bus Owner - Delivery Services',
  },

  {
    // id: 312,
    category: 'Education, Teaching & Library',
    name: 'Admins-Post-Second/Vocation',
    value: 'Admins-Post-Second/Vocation',
  },
  {
    // id: 313,
    category: 'Education, Teaching & Library',
    name: 'Sch Principals/Admin Elem/Sec',
    value: 'Sch Principals/Admin Elem/Sec',
  },
  {
    // id: 511,
    category: 'Education, Teaching & Library',
    name: 'Mgr-Library/Museum/Art',
    value: 'Mgr-Library/Museum/Art',
  },
  {
    // id: 1213,
    category: 'Education, Teaching & Library',
    name: 'Supervisors-Library/Correspond',
    value: 'Supervisors-Library/Correspond',
  },
  {
    // id: 1451,
    category: 'Education, Teaching & Library',
    name: 'Clerk-Library',
    value: 'Clerk-Library',
  },
  {
    // id: 2271,
    category: 'Education, Teaching & Library',
    name: 'Instructors-Air Pilots',
    value: 'Instructors-Air Pilots',
  },
  {
    // id: 4121,
    category: 'Education, Teaching & Library',
    name: 'University Professors',
    value: 'University Professors',
  },
  {
    // id: 4122,
    category: 'Education, Teaching & Library',
    name: 'Teacher-Post-Second/Research',
    value: 'Teacher-Post-Second/Research',
  },
  {
    // id: 4131,
    category: 'Education, Teaching & Library',
    name: 'Teacher-College/Other Vocation',
    value: 'Teacher-College/Other Vocation',
  },
  {
    // id: 4141,
    category: 'Education, Teaching & Library',
    name: 'Teacher-Secondary Sch',
    value: 'Teacher-Secondary Sch',
  },
  {
    // id: 4142,
    category: 'Education, Teaching & Library',
    name: 'Teacher-Elementary Sch/Kinder',
    value: 'Teacher-Elementary Sch/Kinder',
  },
  {
    // id: 4143,
    category: 'Education, Teaching & Library',
    name: 'Counsellor-Education',
    value: 'Counsellor-Education',
  },
  {
    // id: 4166,
    category: 'Education, Teaching & Library',
    name: 'Consult-Educ Policy Research',
    value: 'Consult-Educ Policy Research',
  },
  {
    // id: 4214,
    category: 'Education, Teaching & Library',
    name: 'Teacher-Early Childhood/Asst',
    value: 'Teacher-Early Childhood/Asst',
  },
  {
    // id: 4215,
    category: 'Education, Teaching & Library',
    name: 'Instructors-Per with Disabled',
    value: 'Instructors-Per with Disabled',
  },
  {
    // id: 4216,
    category: 'Education, Teaching & Library',
    name: 'Instructors-Other',
    value: 'Instructors-Other',
  },
  {
    // id: 5111,
    category: 'Education, Teaching & Library',
    name: 'Librarians',
    value: 'Librarians',
  },
  {
    // id: 5113,
    category: 'Education, Teaching & Library',
    name: 'Archivists',
    value: 'Archivists',
  },
  {
    // id: 5211,
    category: 'Education, Teaching & Library',
    name: 'Assistant-Library/Archive Tech',
    value: 'Assistant-Library/Archive Tech',
  },
  {
    // id: 6472,
    category: 'Education, Teaching & Library',
    name: 'Assistant-Elem/Second School',
    value: 'Assistant-Elem/Second School',
  },

  {
    // id: 811,
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Primary Prod (Except agri)',
    value: 'Mgr-Primary Prod (Except agri)',
  },
  {
    // id: 2122,
    category: 'Fishing, Forestry & Mining',
    name: 'Forestry Professional',
    value: 'Forestry Professional',
  },
  {
    // id: 2143,
    category: 'Fishing, Forestry & Mining',
    name: 'Engineer-Mining',
    value: 'Engineer-Mining',
  },
  {
    // id: 2223,
    category: 'Fishing, Forestry & Mining',
    name: 'Technician-Forestry',
    value: 'Technician-Forestry',
  },
  {
    // id: 2224,
    category: 'Fishing, Forestry & Mining',
    name: 'Officer-Conservation/Fishery',
    value: 'Officer-Conservation/Fishery',
  },
  {
    // id: 7372,
    category: 'Fishing, Forestry & Mining',
    name: 'Drillers/Blast/Mine/Quarry',
    value: 'Drillers/Blast/Mine/Quarry',
  },
  {
    // id: 7451,
    category: 'Fishing, Forestry & Mining',
    name: 'Longshore Workers',
    value: 'Longshore Workers',
  },
  {
    // id: 8211,
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Logging/Forestry',
    value: 'Mgr-Logging/Forestry',
  },
  {
    // id: 8221,
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Mining/Quarrying',
    value: 'Mgr-Mining/Quarrying',
  },
  {
    // id: 8231,
    category: 'Fishing, Forestry & Mining',
    name: 'Development Miners',
    value: 'Development Miners',
  },
  {
    // id: 8241,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Logging Machinery',
    value: 'Operator-Logging Machinery',
  },
  {
    // id: 8261,
    category: 'Fishing, Forestry & Mining',
    name: 'Officer-Fishing Masters',
    value: 'Officer-Fishing Masters',
  },
  {
    // id: 8262,
    category: 'Fishing, Forestry & Mining',
    name: 'Fishing Vessel Skippers/Fisher',
    value: 'Fishing Vessel Skippers/Fisher',
  },
  {
    // id: 8411,
    category: 'Fishing, Forestry & Mining',
    name: 'Underground Mine Workers',
    value: 'Underground Mine Workers',
  },
  {
    // id: 8421,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Chain Saw/Skidder',
    value: 'Operator-Chain Saw/Skidder',
  },
  {
    // id: 8422,
    category: 'Fishing, Forestry & Mining',
    name: 'Silviculture/Forestry Workers',
    value: 'Silviculture/Forestry Workers',
  },
  {
    // id: 8441,
    category: 'Fishing, Forestry & Mining',
    name: 'Fishing Vessel Deckhand',
    value: 'Fishing Vessel Deckhand',
  },
  {
    // id: 8442,
    category: 'Fishing, Forestry & Mining',
    name: 'Trappers/Hunters',
    value: 'Trappers/Hunters',
  },
  {
    // id: 8614,
    category: 'Fishing, Forestry & Mining',
    name: 'Mine Labourers',
    value: 'Mine Labourers',
  },
  {
    // id: 8616,
    category: 'Fishing, Forestry & Mining',
    name: 'Logging/Forestry Labourers',
    value: 'Logging/Forestry Labourers',
  },
  {
    // id: 9211,
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Mineral/Metal Processing',
    value: 'Mgr-Mineral/Metal Processing',
  },
  {
    // id: 9215,
    category: 'Fishing, Forestry & Mining',
    name: 'Mgr-Forest Products Process',
    value: 'Mgr-Forest Products Process',
  },
  {
    // id: 9233,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Pulping Control',
    value: 'Operator-Pulping Control',
  },
  {
    // id: 9415,
    category: 'Fishing, Forestry & Mining',
    name: 'Testers/Mineral/Metal Process',
    value: 'Testers/Mineral/Metal Process',
  },
  {
    // id: 9431,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Sawmill Machine',
    value: 'Operator-Sawmill Machine',
  },
  {
    // id: 9432,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Pulp Mill Machine',
    value: 'Operator-Pulp Mill Machine',
  },
  {
    // id: 9434,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Wood Process Other',
    value: 'Operator-Wood Process Other',
  },
  {
    // id: 9436,
    category: 'Fishing, Forestry & Mining',
    name: 'Lumber Graders/Other Wood',
    value: 'Lumber Graders/Other Wood',
  },
  {
    // id: 9463,
    category: 'Fishing, Forestry & Mining',
    name: 'Fish Plant Workers',
    value: 'Fish Plant Workers',
  },
  {
    // id: 9513,
    category: 'Fishing, Forestry & Mining',
    name: 'Operator-Woodworking Machine',
    value: 'Operator-Woodworking Machine',
  },
  {
    // id: 9614,
    category: 'Fishing, Forestry & Mining',
    name: 'Labourer - Wood/Pulp Process',
    value: 'Labourer - Wood/Pulp Process',
  },
  {
    // id: 9618,
    category: 'Fishing, Forestry & Mining',
    name: 'Fish Processing Labourer',
    value: 'Fish Processing Labourer',
  },

  {
    // id: 631,
    category: 'Food Preparation & Serving',
    name: 'Mgr-Restaurant/Food Service',
    value: 'Mgr-Restaurant/Food Service',
  },
  {
    // id: 6212,
    category: 'Food Preparation & Serving',
    name: 'Mgr-Food Service',
    value: 'Mgr-Food Service',
  },
  {
    // id: 6241,
    category: 'Food Preparation & Serving',
    name: 'Chefs',
    value: 'Chefs',
  },
  {
    // id: 6242,
    category: 'Food Preparation & Serving',
    name: 'Cooks',
    value: 'Cooks',
  },
  {
    // id: 6251,
    category: 'Food Preparation & Serving',
    name: 'Butchers/Meat Cutters/Fish',
    value: 'Butchers/Meat Cutters/Fish',
  },
  {
    // id: 6252,
    category: 'Food Preparation & Serving',
    name: 'Bakers',
    value: 'Bakers',
  },
  {
    // id: 6452,
    category: 'Food Preparation & Serving',
    name: 'Bartenders',
    value: 'Bartenders',
  },
  {
    // id: 6453,
    category: 'Food Preparation & Serving',
    name: 'Food/Beverage Servers',
    value: 'Food/Beverage Servers',
  },
  {
    // id: 6453,
    category: 'Food Preparation & Serving',
    name: 'Coffee servers/baristas',
    value: 'Coffee servers/baristas',
  },
  {
    // id: 6453,
    category: 'Food Preparation & Serving',
    name: 'Waiters/Waitresses',
    value: 'Waiters/Waitresses',
  },
  {
    // id: 6622,
    category: 'Food Preparation & Serving',
    name: 'Clerk-Grocery/Store Stockers',
    value: 'Clerk-Grocery/Store Stockers',
  },
  {
    // id: 6641,
    category: 'Food Preparation & Serving',
    name: 'Food Counter Attend/Kitchen',
    value: 'Food Counter Attend/Kitchen',
  },
  {
    // id: 9213,
    category: 'Food Preparation & Serving',
    name: 'Mgr-Food/Bev/Tobacco Process',
    value: 'Mgr-Food/Bev/Tobacco Process',
  },
  {
    // id: 9461,
    category: 'Food Preparation & Serving',
    name: 'MachOper/Food/Beverage Process',
    value: 'MachOper/Food/Beverage Process',
  },
  {
    // id: 9462,
    category: 'Food Preparation & Serving',
    name: 'Butchers/Meat Cutters/Poultry',
    value: 'Butchers/Meat Cutters/Poultry',
  },
  {
    // id: 9465,
    category: 'Food Preparation & Serving',
    name: 'Testers/Graders/Food/Bev Proc',
    value: 'Testers/Graders/Food/Bev Proc',
  },
  {
    // id: 9617,
    category: 'Food Preparation & Serving',
    name: 'Labourer Food/Beverage/Tobacco',
    value: 'Labourer Food/Beverage/Tobacco',
  },
  {
    // id: 9912,
    category: 'Food Preparation & Serving',
    name: 'Business Owner - Food Services',
    value: 'Business Owner - Food Services',
  },

  {
    // id: 11,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Legislators/Political Leaders',
    value: 'Legislators/Political Leaders',
  },
  {
    // id: 411,
    category: 'Government - Federal/ Provincial and Municipal',
    name: "Mgr-Gov't/ Admin-Health/Soc",
    value: "Mgr-Gov't/ Admin-Health/Soc",
  },
  {
    // id: 412,
    category: 'Government - Federal/ Provincial and Municipal',
    name: "Mgr-Gov't-Econ Policy",
    value: "Mgr-Gov't-Econ Policy",
  },
  {
    // id: 413,
    category: 'Government - Federal/ Provincial and Municipal',
    name: "Mgr-Gov't/Admin-Educ Policy",
    value: "Mgr-Gov't/Admin-Educ Policy",
  },
  {
    // id: 4152,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Social Workers',
    value: 'Social Workers',
  },
  {
    // id: 4169,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Social Science-Other',
    value: 'Social Science-Other',
  },
  {
    // id: 5125,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Translators/Interpreters',
    value: 'Translators/Interpreters',
  },
  {
    // id: 7422,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Oper-Public Works Mtce equip',
    value: 'Oper-Public Works Mtce equip',
  },
  {
    // id: 7442,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Waterworks/Gas Mtce Workers',
    value: 'Waterworks/Gas Mtce Workers',
  },
  {
    // id: 7621,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Public Works/Mtce Labourers',
    value: 'Public Works/Mtce Labourers',
  },
  {
    // id: 9424,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Operator-Water/Waste Plant',
    value: 'Operator-Water/Waste Plant',
  },
  {
    // id: 9902,
    category: 'Government - Federal/ Provincial and Municipal',
    name: 'Aboriginal Affairs Administ',
    value: 'Aboriginal Affairs Administ',
  },

  {
    // id: 311,
    category: 'Healthcare',
    name: 'Mgr-Health Care',
    value: 'Mgr-Health Care',
  },
  {
    // id: 1243,
    category: 'Healthcare',
    name: 'Secretaries-Medical',
    value: 'Secretaries-Medical',
  },
  {
    // id: 2115,
    category: 'Healthcare',
    name: 'Oth.Prof Occup in Phys Science',
    value: 'Oth.Prof Occup in Phys Science',
  },
  {
    // id: 2263,
    category: 'Healthcare',
    name: 'Inspector-Env Health/Safety',
    value: 'Inspector-Env Health/Safety',
  },
  {
    // id: 3111,
    category: 'Healthcare',
    name: 'Physician-Specialist',
    value: 'Physician-Specialist',
  },
  {
    // id: 3112,
    category: 'Healthcare',
    name: 'Physician-General/Family',
    value: 'Physician-General/Family',
  },
  {
    // id: 3113,
    category: 'Healthcare',
    name: 'Dentists',
    value: 'Dentists',
  },
  {
    // id: 3114,
    category: 'Healthcare',
    name: 'Veterinarians',
    value: 'Veterinarians',
  },
  {
    // id: 3121,
    category: 'Healthcare',
    name: 'Optometrists',
    value: 'Optometrists',
  },
  {
    // id: 3122,
    category: 'Healthcare',
    name: 'Chiropractors',
    value: 'Chiropractors',
  },
  {
    // id: 3123,
    category: 'Healthcare',
    name: 'Other Health Diagnose/Treating',
    value: 'Other Health Diagnose/Treating',
  },
  {
    // id: 3131,
    category: 'Healthcare',
    name: 'Pharmacists',
    value: 'Pharmacists',
  },
  {
    // id: 3132,
    category: 'Healthcare',
    name: 'Dietitians/Nutritionists',
    value: 'Dietitians/Nutritionists',
  },
  {
    // id: 3141,
    category: 'Healthcare',
    name: 'Audiologists/Speech-Language',
    value: 'Audiologists/Speech-Language',
  },
  {
    // id: 3142,
    category: 'Healthcare',
    name: 'Physiotherapists',
    value: 'Physiotherapists',
  },
  {
    // id: 3143,
    category: 'Healthcare',
    name: 'Occupational Therapists',
    value: 'Occupational Therapists',
  },
  {
    // id: 3144,
    category: 'Healthcare',
    name: 'Other in Therapy/Assessment',
    value: 'Other in Therapy/Assessment',
  },
  {
    // id: 3151,
    category: 'Healthcare',
    name: 'Nurses-Head/Supervisor',
    value: 'Nurses-Head/Supervisor',
  },
  {
    // id: 3152,
    category: 'Healthcare',
    name: 'Nurses-Registered',
    value: 'Nurses-Registered',
  },
  {
    // id: 3211,
    category: 'Healthcare',
    name: 'Assistant-Medical Lab. Tech',
    value: 'Assistant-Medical Lab. Tech',
  },
  {
    // id: 3212,
    category: 'Healthcare',
    name: 'Technician-Medical Laboratory',
    value: 'Technician-Medical Laboratory',
  },
  {
    // id: 3213,
    category: 'Healthcare',
    name: 'Technician-Vet/Animal Health',
    value: 'Technician-Vet/Animal Health',
  },
  {
    // id: 3214,
    category: 'Healthcare',
    name: 'Respiratory/Perfusion/Cardio',
    value: 'Respiratory/Perfusion/Cardio',
  },
  {
    // id: 3215,
    category: 'Healthcare',
    name: 'Technologist-Medical Radiation',
    value: 'Technologist-Medical Radiation',
  },
  {
    // id: 3216,
    category: 'Healthcare',
    name: 'Medical Sonographers',
    value: 'Medical Sonographers',
  },
  {
    // id: 3217,
    category: 'Healthcare',
    name: 'Technologist-Cardiology',
    value: 'Technologist-Cardiology',
  },
  {
    // id: 3218,
    category: 'Healthcare',
    name: 'Electroencephalographic/Other',
    value: 'Electroencephalographic/Other',
  },
  {
    // id: 3219,
    category: 'Healthcare',
    name: 'Technologist-Other Medical',
    value: 'Technologist-Other Medical',
  },
  {
    // id: 3221,
    category: 'Healthcare',
    name: 'Denturists',
    value: 'Denturists',
  },
  {
    // id: 3222,
    category: 'Healthcare',
    name: 'Dental Hygienists/Therapists',
    value: 'Dental Hygienists/Therapists',
  },
  {
    // id: 3223,
    category: 'Healthcare',
    name: 'Technician-Dental/Lab Bench',
    value: 'Technician-Dental/Lab Bench',
  },
  {
    // id: 3231,
    category: 'Healthcare',
    name: 'Opticians',
    value: 'Opticians',
  },
  {
    // id: 3232,
    category: 'Healthcare',
    name: 'Midwives/Natural Healing',
    value: 'Midwives/Natural Healing',
  },
  {
    // id: 3233,
    category: 'Healthcare',
    name: 'Nurses-Licensed Practical',
    value: 'Nurses-Licensed Practical',
  },
  {
    // id: 3234,
    category: 'Healthcare',
    name: 'Attendant-Ambulance',
    value: 'Attendant-Ambulance',
  },
  {
    // id: 1244,
    category: 'Healthcare',
    name: 'Medical Transcriptionists',
    value: 'Medical Transcriptionists',
  },
  {
    // id: 3235,
    category: 'Healthcare',
    name: 'Other Therapists/Assessment',
    value: 'Other Therapists/Assessment',
  },
  {
    // id: 3411,
    category: 'Healthcare',
    name: 'Dental Assistants',
    value: 'Dental Assistants',
  },
  {
    // id: 3413,
    category: 'Healthcare',
    name: 'Nurse-Aides/Orderlies',
    value: 'Nurse-Aides/Orderlies',
  },
  {
    // id: 3414,
    category: 'Healthcare',
    name: 'Health Service-Other Support',
    value: 'Health Service-Other Support',
  },
  {
    // id: 4151,
    category: 'Healthcare',
    name: 'Psychologists',
    value: 'Psychologists',
  },
  {
    // id: 4165,
    category: 'Healthcare',
    name: 'Consult-Health Policy Research',
    value: 'Consult-Health Policy Research',
  },
  {
    // id: 9931,
    category: 'Healthcare',
    name: 'Bus Owner - Health Services',
    value: 'Bus Owner - Health Services',
  },

  {
    // id: 6213,
    category: 'Janitorial & Cleaning Services',
    name: 'Executive Housekeepers',
    value: 'Executive Housekeepers',
  },
  {
    // id: 6214,
    category: 'Janitorial & Cleaning Services',
    name: 'Mgr-Dry Cleaning/Laundry',
    value: 'Mgr-Dry Cleaning/Laundry',
  },
  {
    // id: 6215,
    category: 'Janitorial & Cleaning Services',
    name: 'Mgr-Cleaning Supervisor',
    value: 'Mgr-Cleaning Supervisor',
  },
  {
    // id: 6471,
    category: 'Janitorial & Cleaning Services',
    name: 'Visiting Homemakers/Housekeep',
    value: 'Visiting Homemakers/Housekeep',
  },
  {
    // id: 6661,
    category: 'Janitorial & Cleaning Services',
    name: 'Cleaner-Light Duty',
    value: 'Cleaner-Light Duty',
  },
  {
    // id: 6662,
    category: 'Janitorial & Cleaning Services',
    name: 'Cleaner-Specialized',
    value: 'Cleaner-Specialized',
  },
  {
    // id: 6663,
    category: 'Janitorial & Cleaning Services',
    name: 'Janitors/Caretakers',
    value: 'Janitors/Caretakers',
  },
  {
    // id: 6681,
    category: 'Janitorial & Cleaning Services',
    name: 'Dry Cleaning/Laundry worker',
    value: 'Dry Cleaning/Laundry worker',
  },
  {
    // id: 6682,
    category: 'Janitorial & Cleaning Services',
    name: 'Ironing/Pressing/Finishing Occ',
    value: 'Ironing/Pressing/Finishing Occ',
  },
  {
    // id: 7444,
    category: 'Janitorial & Cleaning Services',
    name: 'Pest Controllers/Fumigators',
    value: 'Pest Controllers/Fumigators',
  },
  {
    // id: 9932,
    category: 'Janitorial & Cleaning Services',
    name: 'Bus Owner - Janitorial/Clean',
    value: 'Bus Owner - Janitorial/Clean',
  },
  {
    // id: 9940,
    category: 'Janitorial & Cleaning Services',
    name: 'Septic/Recycle/Garbage Services',
    value: 'Septic/Recycle/Garbage Services',
  },

  {
    // id: 1242,
    category: 'Legal',
    name: 'Legal Secretaries',
    value: 'Legal Secretaries',
  },
  {
    // id: 1244,
    category: 'Legal',
    name: 'Court Recorders',
    value: 'Court Recorders',
  },
  {
    // id: 1443,
    category: 'Legal',
    name: 'Clerk-Court',
    value: 'Clerk-Court',
  },
  {
    // id: 4111,
    category: 'Legal',
    name: 'Judges',
    value: 'Judges',
  },
  {
    // id: 4112,
    category: 'Legal',
    name: 'Lawyers/Quebec Notaries',
    value: 'Lawyers/Quebec Notaries',
  },
  {
    // id: 4211,
    category: 'Legal',
    name: 'Paralegal/Related Occupation',
    value: 'Paralegal/Related Occupation',
  },

  {
    // id: 721,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Facility Oper/Mtce',
    value: 'Mgr-Facility Oper/Mtce',
  },
  {
    // id: 911,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Manufacturing',
    value: 'Mgr-Manufacturing',
  },
  {
    // id: 7211,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr/Machinists/Related Occup',
    value: 'Mgr/Machinists/Related Occup',
  },
  {
    // id: 7214,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Contractor-Mgr/Metal Forming',
    value: 'Contractor-Mgr/Metal Forming',
  },
  {
    // id: 7231,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Machinists/Tooling',
    value: 'Inspector-Machinists/Tooling',
  },
  {
    // id: 7232,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Tool/Die Makers',
    value: 'Tool/Die Makers',
  },
  {
    // id: 7261,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Sheet Metal Workers',
    value: 'Sheet Metal Workers',
  },
  {
    // id: 7262,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Boilermakers',
    value: 'Boilermakers',
  },
  {
    // id: 7263,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Struct Metal/Platework Fabric',
    value: 'Struct Metal/Platework Fabric',
  },
  {
    // id: 7264,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Ironworkers',
    value: 'Ironworkers',
  },
  {
    // id: 7266,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Blacksmiths/Die Setters',
    value: 'Blacksmiths/Die Setters',
  },
  {
    // id: 7292,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Glaziers',
    value: 'Glaziers',
  },
  {
    // id: 7316,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Machine Fitters',
    value: 'Machine Fitters',
  },
  {
    // id: 7452,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Material Handler',
    value: 'Material Handler',
  },
  {
    // id: 9214,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Plastic/Rubber Products ',
    value: 'Mgr-Plastic/Rubber Products ',
  },
  {
    // id: 9221,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Motor Veh/Machine Repair',
    value: 'Mgr-Motor Veh/Machine Repair',
  },
  {
    // id: 9222,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Electronics Manufacture',
    value: 'Mgr-Electronics Manufacture',
  },
  {
    // id: 9223,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Elec Products Manufacture',
    value: 'Mgr-Elec Products Manufacture',
  },
  {
    // id: 9226,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Other Mech/Metal',
    value: 'Mgr-Other Mech/Metal',
  },
  {
    // id: 9227,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mgr-Other Products Manufactr',
    value: 'Mgr-Other Products Manufactr',
  },
  {
    // id: 9231,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mineral/Metal Process Manfuctr',
    value: 'Mineral/Metal Process Manfuctr',
  },
  {
    // id: 9234,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Papermaking/Coating',
    value: 'Operator-Papermaking/Coating',
  },
  {
    // id: 9411,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper/Mineral/Metal Proces',
    value: 'Mach Oper/Mineral/Metal Proces',
  },
  {
    // id: 9412,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Foundry Workers',
    value: 'Foundry Workers',
  },
  {
    // id: 9413,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Oper-Glass Forming/Finishing',
    value: 'Oper-Glass Forming/Finishing',
  },
  {
    // id: 9422,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Plastics Process Mach',
    value: 'Operator-Plastics Process Mach',
  },
  {
    // id: 9423,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Rubber Process Mach',
    value: 'Operator-Rubber Process Mach',
  },
  {
    // id: 9433,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Papermake/Finish Mach',
    value: 'Operator-Papermake/Finish Mach',
  },
  {
    // id: 9435,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Other-Paper Converting Mach',
    value: 'Other-Paper Converting Mach',
  },
  {
    // id: 9464,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Tobacco Processing Mach Oper',
    value: 'Tobacco Processing Mach Oper',
  },
  {
    // id: 9473,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Oper-Binding/Finishing Machine',
    value: 'Oper-Binding/Finishing Machine',
  },
  {
    // id: 9481,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Aircraft Assemblers',
    value: 'Inspector-Aircraft Assemblers',
  },
  {
    // id: 9482,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Motor/Machine',
    value: 'Inspector-Motor/Machine',
  },
  {
    // id: 9483,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Electros Assembler/fabricators',
    value: 'Electros Assembler/fabricators',
  },
  {
    // id: 9484,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Elec Appliance Manfc',
    value: 'Inspector-Elec Appliance Manfc',
  },
  {
    // id: 9485,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Industrial Elec Motors Assem',
    value: 'Industrial Elec Motors Assem',
  },
  {
    // id: 9486,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Mechanic Assemblers',
    value: 'Inspector-Mechanic Assemblers',
  },
  {
    // id: 9487,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper/Elec Apparatus',
    value: 'Mach Oper/Elec Apparatus',
  },
  {
    // id: 9491,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Boat Assemblers',
    value: 'Inspector-Boat Assemblers',
  },
  {
    // id: 9492,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Furniture/Fixture Assemblers',
    value: 'Furniture/Fixture Assemblers',
  },
  {
    // id: 9493,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Other Wood Products Assemblers',
    value: 'Other Wood Products Assemblers',
  },
  {
    // id: 9494,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Furniture Finishers/Refinisher',
    value: 'Furniture Finishers/Refinisher',
  },
  {
    // id: 9495,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Plastic Prods Assemble/Finish',
    value: 'Plastic Prods Assemble/Finish',
  },
  {
    // id: 9496,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Painters/Coaters-Industrial',
    value: 'Painters/Coaters-Industrial',
  },
  {
    // id: 9497,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Plating/Metal Spraying',
    value: 'Plating/Metal Spraying',
  },
  {
    // id: 9498,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Inspector-Other Assemblers',
    value: 'Inspector-Other Assemblers',
  },
  {
    // id: 9511,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Machining Tool',
    value: 'Operator-Machining Tool',
  },
  {
    // id: 9512,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Forging Machine',
    value: 'Operator-Forging Machine',
  },
  {
    // id: 9514,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Operator-Metalworking Machine',
    value: 'Operator-Metalworking Machine',
  },
  {
    // id: 9516,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper-Other Metal Products',
    value: 'Mach Oper-Other Metal Products',
  },
  {
    // id: 9517,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Mach Oper-Other Product',
    value: 'Mach Oper-Other Product',
  },
  {
    // id: 9611,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourers Mineral/Metal Proces',
    value: 'Labourers Mineral/Metal Proces',
  },
  {
    // id: 9612,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourers in Metal Fabrication',
    value: 'Labourers in Metal Fabrication',
  },
  {
    // id: 9613,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourers Chemical Process',
    value: 'Labourers Chemical Process',
  },
  {
    // id: 9615,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourer Rubber/Plastic Prod',
    value: 'Labourer Rubber/Plastic Prod',
  },
  {
    // id: 9619,
    category: 'Manufacturing & Manufacturing Related',
    name: 'Labourer-Other Process/Manu',
    value: 'Labourer-Other Process/Manu',
  },

  {
    // id: 112,
    category: 'Office & Admin',
    name: 'Mgr-Human Resources',
    value: 'Mgr-Human Resources',
  },
  {
    // id: 114,
    category: 'Office & Admin',
    name: 'Mgr-Other Admin Service',
    value: 'Mgr-Other Admin Service',
  },
  {
    // id: 414,
    category: 'Office & Admin',
    name: 'Mgr-Other Public Admin',
    value: 'Mgr-Other Public Admin',
  },
  {
    // id: 1121,
    category: 'Office & Admin',
    name: 'Specialists-Human Resources',
    value: 'Specialists-Human Resources',
  },
  {
    // id: 1211,
    category: 'Office & Admin',
    name: 'Supervisors-General Office',
    value: 'Supervisors-General Office',
  },
  {
    // id: 1221,
    category: 'Office & Admin',
    name: 'Officer-Adminstration',
    value: 'Officer-Adminstration',
  },
  {
    // id: 1222,
    category: 'Office & Admin',
    name: 'Assistant-Executive',
    value: 'Assistant-Executive',
  },
  {
    // id: 1223,
    category: 'Office & Admin',
    name: 'Officer-Personnel/Recruitment',
    value: 'Officer-Personnel/Recruitment',
  },
  {
    // id: 1241,
    category: 'Office & Admin',
    name: 'Secretaries (Except Legal/Med)',
    value: 'Secretaries (Except Legal/Med)',
  },
  {
    // id: 1411,
    category: 'Office & Admin',
    name: 'Clerk-General Office',
    value: 'Clerk-General Office',
  },
  {
    // id: 1413,
    category: 'Office & Admin',
    name: 'Clerk-Records mgmt/Filing',
    value: 'Clerk-Records mgmt/Filing',
  },
  {
    // id: 1414,
    category: 'Office & Admin',
    name: 'Receptionists/Switchboard Oper',
    value: 'Receptionists/Switchboard Oper',
  },
  {
    // id: 1422,
    category: 'Office & Admin',
    name: 'Clerk-Data Entry',
    value: 'Clerk-Data Entry',
  },
  {
    // id: 1431,
    category: 'Office & Admin',
    name: 'Clerk-Accounting/Related',
    value: 'Clerk-Accounting/Related',
  },
  {
    // id: 1432,
    category: 'Office & Admin',
    name: 'Clerk-Payroll',
    value: 'Clerk-Payroll',
  },
  {
    // id: 1441,
    category: 'Office & Admin',
    name: 'Clerk-Administrative',
    value: 'Clerk-Administrative',
  },
  {
    // id: 1442,
    category: 'Office & Admin',
    name: 'Clerk-Personnel',
    value: 'Clerk-Personnel',
  },
  {
    // id: 1452,
    category: 'Office & Admin',
    name: 'Clerk-Correspond/Publication',
    value: 'Clerk-Correspond/Publication',
  },
  {
    // id: 1453,
    category: 'Office & Admin',
    name: 'Clerk-Customer Service/Inform',
    value: 'Clerk-Customer Service/Inform',
  },
  {
    // id: 1454,
    category: 'Office & Admin',
    name: 'Clerk-Survey Interview/Stat',
    value: 'Clerk-Survey Interview/Stat',
  },
  {
    // id: 1473,
    category: 'Office & Admin',
    name: 'Clerk-Production',
    value: 'Clerk-Production',
  },
  {
    // id: 1474,
    category: 'Office & Admin',
    name: 'Clerk-Purchasing/Inventory',
    value: 'Clerk-Purchasing/Inventory',
  },

  {
    // id: 2144,
    category: 'Oil/Gas/Natural Resources',
    name: 'Engineer-Geological',
    value: 'Engineer-Geological',
  },
  {
    // id: 2145,
    category: 'Oil/Gas/Natural Resources',
    name: 'Engineer-Petroleum',
    value: 'Engineer-Petroleum',
  },
  {
    // id: 2212,
    category: 'Oil/Gas/Natural Resources',
    name: 'Technician-Geo/Mineral',
    value: 'Technician-Geo/Mineral',
  },
  {
    // id: 2255,
    category: 'Oil/Gas/Natural Resources',
    name: 'Technician-Mapping/Related',
    value: 'Technician-Mapping/Related',
  },
  {
    // id: 7373,
    category: 'Oil/Gas/Natural Resources',
    name: 'Water Well Drillers',
    value: 'Water Well Drillers',
  },
  {
    // id: 8222,
    category: 'Oil/Gas/Natural Resources',
    name: 'Mgr-Oil/Gas/NatRes Drillers',
    value: 'Mgr-Oil/Gas/NatRes Drillers',
  },
  {
    // id: 8232,
    category: 'Oil/Gas/Natural Resources',
    name: 'Oil/Gas/NatRes Drill service',
    value: 'Oil/Gas/NatRes Drill service',
  },
  {
    // id: 8412,
    category: 'Oil/Gas/Natural Resources',
    name: 'Oil/Gas/NatRes Well Drill Wrkr',
    value: 'Oil/Gas/NatRes Well Drill Wrkr',
  },
  {
    // id: 8615,
    category: 'Oil/Gas/Natural Resources',
    name: 'Oil/Gas/NatRes Gas Drill/Serv',
    value: 'Oil/Gas/NatRes Gas Drill/Serv',
  },
  {
    // id: 9212,
    category: 'Oil/Gas/Natural Resources',
    name: 'Mgr-Petro/Gas/Chemical Process',
    value: 'Mgr-Petro/Gas/Chemical Process',
  },
  {
    // id: 9232,
    category: 'Oil/Gas/Natural Resources',
    name: 'Operator-Petroleum/Gas/Chemicl',
    value: 'Operator-Petroleum/Gas/Chemicl',
  },
  {
    // id: 9421,
    category: 'Oil/Gas/Natural Resources',
    name: 'Operator-Chemical Plant Mach',
    value: 'Operator-Chemical Plant Mach',
  },
  {
    // id: 9933,
    category: 'Oil/Gas/Natural Resources',
    name: 'Bus Owner - Oil/Gas',
    value: 'Bus Owner - Oil/Gas',
  },
  {
    // id: 9939,
    category: 'Oil/Gas/Natural Resources',
    name: 'Consultant - Oil/Gas/Nat Res',
    value: 'Consultant - Oil/Gas/Nat Res',
  },
  {
    // id: 7382,
    category: 'Oil/Gas/Natural Resources',
    name: 'Commercial Divers',
    value: 'Commercial Divers',
  },

  {
    // id: 314,
    category: 'Protective Services',
    name: 'Mgr-Social Comm/Correctional',
    value: 'Mgr-Social Comm/Correctional',
  },
  {
    // id: 641,
    category: 'Protective Services',
    name: 'Officer-Commissioned Police',
    value: 'Officer-Commissioned Police',
  },
  {
    // id: 642,
    category: 'Protective Services',
    name: 'Fire Chiefs/Senior Firefighters',
    value: 'Fire Chiefs/Senior Firefighters',
  },
  {
    // id: 643,
    category: 'Protective Services',
    name: 'Officer-Armed Forces',
    value: 'Officer-Armed Forces',
  },
  {
    // id: 1227,
    category: 'Protective Services',
    name: 'Officer-Court/Justices Peace',
    value: 'Officer-Court/Justices Peace',
  },
  {
    // id: 1228,
    category: 'Protective Services',
    name: 'Officer-Immigration/EI/Reven',
    value: 'Officer-Immigration/EI/Reven',
  },
  {
    // id: 1475,
    category: 'Protective Services',
    name: 'Operator-Dispatchers/Radio',
    value: 'Operator-Dispatchers/Radio',
  },
  {
    // id: 4155,
    category: 'Protective Services',
    name: 'Officer-Probation/Parole',
    value: 'Officer-Probation/Parole',
  },
  {
    // id: 4168,
    category: 'Protective Services',
    name: "Officer-Prog Unique to Gov't",
    value: "Officer-Prog Unique to Gov't",
  },
  {
    // id: 6261,
    category: 'Protective Services',
    name: 'Officer-Police',
    value: 'Officer-Police',
  },
  {
    // id: 6262,
    category: 'Protective Services',
    name: 'Firefighters',
    value: 'Firefighters',
  },
  {
    // id: 6461,
    category: 'Protective Services',
    name: 'Sheriffs/Bailiffs',
    value: 'Sheriffs/Bailiffs',
  },
  {
    // id: 6462,
    category: 'Protective Services',
    name: 'Officer-Correctional Service',
    value: 'Officer-Correctional Service',
  },
  {
    // id: 6463,
    category: 'Protective Services',
    name: 'Officer-By-Law Enforce/Other',
    value: 'Officer-By-Law Enforce/Other',
  },
  {
    // id: 6464,
    category: 'Protective Services',
    name: 'Armed Forces-Occup Unique',
    value: 'Armed Forces-Occup Unique',
  },
  {
    // id: 6465,
    category: 'Protective Services',
    name: 'Officer-Other Protective',
    value: 'Officer-Other Protective',
  },
  {
    // id: 6651,
    category: 'Protective Services',
    name: 'Security Guard Related Occupations',
    value: 'Security Guard Related Occupations',
  },

  {
    // id: 121,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Mgr-Ins Real Estate Fin Broker',
    value: 'Mgr-Ins Real Estate Fin Broker',
  },
  {
    // id: 1224,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Administrators-Property',
    value: 'Administrators-Property',
  },
  {
    // id: 1233,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Insurance Adjusters/Claims',
    value: 'Insurance Adjusters/Claims',
  },
  {
    // id: 1235,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Assessors/Valuators/Appraisers',
    value: 'Assessors/Valuators/Appraisers',
  },
  {
    // id: 2154,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Land Surveyors',
    value: 'Land Surveyors',
  },
  {
    // id: 2254,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Technician-Land Survey',
    value: 'Technician-Land Survey',
  },
  {
    // id: 6231,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Agent-Insurance/Brokers',
    value: 'Agent-Insurance/Brokers',
  },
  {
    // id: 6232,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Agent-Real Estate/Salespersons',
    value: 'Agent-Real Estate/Salespersons',
  },
  {
    // id: 9934,
    category: 'Real Estate, Insurance & Related Services',
    name: 'Bus Owner - Real Est/Insurance',
    value: 'Bus Owner - Real Est/Insurance',
  },

  {
    // id: 113,
    category: 'Sales & Service',
    name: 'Mgr-Purchasing',
    value: 'Mgr-Purchasing',
  },
  {
    // id: 611,
    category: 'Sales & Service',
    name: 'Mgr-Sales/Mrkt/Adver',
    value: 'Mgr-Sales/Mrkt/Adver',
  },
  {
    // id: 621,
    category: 'Sales & Service',
    name: 'Mgr-Retail Trade',
    value: 'Mgr-Retail Trade',
  },
  {
    // id: 632,
    category: 'Sales & Service',
    name: 'Mgr-Accommodation Service',
    value: 'Mgr-Accommodation Service',
  },
  {
    // id: 1225,
    category: 'Sales & Service',
    name: 'Officer-Purchasing Agent',
    value: 'Officer-Purchasing Agent',
  },
  {
    // id: 1433,
    category: 'Sales & Service',
    name: 'Customer Service Represent',
    value: 'Customer Service Represent',
  },
  {
    // id: 1472,
    category: 'Sales & Service',
    name: 'Clerk-Storekeepers/Parts',
    value: 'Clerk-Storekeepers/Parts',
  },
  {
    // id: 6221,
    category: 'Sales & Service',
    name: 'Technical Sales Specialists',
    value: 'Technical Sales Specialists',
  },
  {
    // id: 6233,
    category: 'Sales & Service',
    name: 'Buyer Retail/Wholesale',
    value: 'Buyer Retail/Wholesale',
  },
  {
    // id: 6411,
    category: 'Sales & Service',
    name: 'Sales Reps-Wholesale Trade',
    value: 'Sales Reps-Wholesale Trade',
  },
  {
    // id: 6421,
    category: 'Sales & Service',
    name: 'Retail Salespersons/SalesClerk',
    value: 'Retail Salespersons/SalesClerk',
  },
  {
    // id: 6435,
    category: 'Sales & Service',
    name: 'Clerk-Hotel Front Desk',
    value: 'Clerk-Hotel Front Desk',
  },
  {
    // id: 6611,
    category: 'Sales & Service',
    name: 'Cashiers/Bank Tellers',
    value: 'Cashiers/Bank Tellers',
  },
  {
    // id: 6621,
    category: 'Sales & Service',
    name: 'Attendant-Service Station',
    value: 'Attendant-Service Station',
  },
  {
    // id: 7343,
    category: 'Sales & Service',
    name: 'Shoe Repairers/Shoemakers',
    value: 'Shoe Repairers/Shoemakers',
  },
  {
    // id: 9224,
    category: 'Sales & Service',
    name: 'Mgr-Furniture/Fixtures',
    value: 'Mgr-Furniture/Fixtures',
  },
  {
    // id: 9911,
    category: 'Sales & Service',
    name: 'Business Owner - Retail',
    value: 'Business Owner - Retail',
  },

  {
    // id: 2111,
    category: 'Science & Scientific Research',
    name: 'Physicists/Astronomers',
    value: 'Physicists/Astronomers',
  },
  {
    // id: 2112,
    category: 'Science & Scientific Research',
    name: 'Chemists',
    value: 'Chemists',
  },
  {
    // id: 2113,
    category: 'Science & Scientific Research',
    name: 'Geologists/Geochemists',
    value: 'Geologists/Geochemists',
  },
  {
    // id: 2114,
    category: 'Science & Scientific Research',
    name: 'Meteorologists',
    value: 'Meteorologists',
  },
  {
    // id: 2121,
    category: 'Science & Scientific Research',
    name: 'Biologists/Related Scientists',
    value: 'Biologists/Related Scientists',
  },
  {
    // id: 2211,
    category: 'Science & Scientific Research',
    name: 'Technician-Chemical',
    value: 'Technician-Chemical',
  },
  {
    // id: 2213,
    category: 'Science & Scientific Research',
    name: 'Technician-Meteorological',
    value: 'Technician-Meteorological',
  },
  {
    // id: 2221,
    category: 'Science & Scientific Research',
    name: 'Technician-Biological',
    value: 'Technician-Biological',
  },
  {
    // id: 4161,
    category: 'Science & Scientific Research',
    name: 'Consultant-Natural/Applied Sci',
    value: 'Consultant-Natural/Applied Sci',
  },
  {
    // id: 9910,
    category: 'Science & Scientific Research',
    name: 'Technician - Environmental',
    value: 'Technician - Environmental',
  },

  {
    // id: 513,
    category: 'Sports, Fitness & Recreation',
    name: 'Dir-Recreation Sports/Services',
    value: 'Dir-Recreation Sports/Services',
  },
  {
    // id: 4167,
    category: 'Sports, Fitness & Recreation',
    name: 'Sports/Recreation/Fitness Prog',
    value: 'Sports/Recreation/Fitness Prog',
  },
  {
    // id: 5251,
    category: 'Sports, Fitness & Recreation',
    name: 'Athletes',
    value: 'Athletes',
  },
  {
    // id: 5252,
    category: 'Sports, Fitness & Recreation',
    name: 'Coaches',
    value: 'Coaches',
  },
  {
    // id: 5253,
    category: 'Sports, Fitness & Recreation',
    name: 'Officials- Sports/Referees',
    value: 'Officials- Sports/Referees',
  },
  {
    // id: 5254,
    category: 'Sports, Fitness & Recreation',
    name: 'Instruct Recreat/Sport/Fitness',
    value: 'Instruct Recreat/Sport/Fitness',
  },
  {
    // id: 6442,
    category: 'Sports, Fitness & Recreation',
    name: 'Guides-OutdoorSport/Recreation',
    value: 'Guides-OutdoorSport/Recreation',
  },
  {
    // id: 6671,
    category: 'Sports, Fitness & Recreation',
    name: 'Oper-Amusemnt/Recreation/Sport',
    value: 'Oper-Amusemnt/Recreation/Sport',
  },
  {
    // id: 9935,
    category: 'Sports, Fitness & Recreation',
    name: 'Bus Owner - Fitness & Rec',
    value: 'Bus Owner - Fitness & Rec',
  },

  {
    // id: 5245,
    category: 'Textiles & Textile Related',
    name: 'Patternmaker-Textile/Leather',
    value: 'Patternmaker-Textile/Leather',
  },
  {
    // id: 7317,
    category: 'Textiles & Textile Related',
    name: 'Textile Machinery mechanic',
    value: 'Textile Machinery mechanic',
  },
  {
    // id: 7341,
    category: 'Textiles & Textile Related',
    name: 'Re/Upholsterers',
    value: 'Re/Upholsterers',
  },
  {
    // id: 7342,
    category: 'Textiles & Textile Related',
    name: 'Tailors/Dressmakers/Furrier',
    value: 'Tailors/Dressmakers/Furrier',
  },
  {
    // id: 9216,
    category: 'Textiles & Textile Related',
    name: 'Mgr-Textile Processing',
    value: 'Mgr-Textile Processing',
  },
  {
    // id: 9225,
    category: 'Textiles & Textile Related',
    name: 'Mgr-Fabric/Fur/Leather',
    value: 'Mgr-Fabric/Fur/Leather',
  },
  {
    // id: 9441,
    category: 'Textiles & Textile Related',
    name: 'Oper-Textile Fibre/Yarn Prep',
    value: 'Oper-Textile Fibre/Yarn Prep',
  },
  {
    // id: 9442,
    category: 'Textiles & Textile Related',
    name: 'Weavers/Knitters/Other Fabric',
    value: 'Weavers/Knitters/Other Fabric',
  },
  {
    // id: 9443,
    category: 'Textiles & Textile Related',
    name: 'Oper-Textile Dyeing/Finishing',
    value: 'Oper-Textile Dyeing/Finishing',
  },
  {
    // id: 9444,
    category: 'Textiles & Textile Related',
    name: 'Textile /Graders/Samplers',
    value: 'Textile /Graders/Samplers',
  },
  {
    // id: 9451,
    category: 'Textiles & Textile Related',
    name: 'Sewing Machine Operator',
    value: 'Sewing Machine Operator',
  },
  {
    // id: 9452,
    category: 'Textiles & Textile Related',
    name: 'Fabric/Fur/Leather Cutters',
    value: 'Fabric/Fur/Leather Cutters',
  },
  {
    // id: 9453,
    category: 'Textiles & Textile Related',
    name: 'Hide/Pelt Processing Workers',
    value: 'Hide/Pelt Processing Workers',
  },
  {
    // id: 9454,
    category: 'Textiles & Textile Related',
    name: 'Testers/Fabric/Fur/Leather',
    value: 'Testers/Fabric/Fur/Leather',
  },
  {
    // id: 9616,
    category: 'Textiles & Textile Related',
    name: 'Labourer Textile Processing',
    value: 'Labourer Textile Processing',
  },

  {
    // id: 713,
    category: 'Travel & Transportation',
    name: 'Mgr-Transportation',
    value: 'Mgr-Transportation',
  },
  {
    // id: 1236,
    category: 'Travel & Transportation',
    name: 'Customs/Ship/Other Brokers',
    value: 'Customs/Ship/Other Brokers',
  },
  {
    // id: 1476,
    category: 'Travel & Transportation',
    name: 'Trans Route/Crew Schedulers',
    value: 'Trans Route/Crew Schedulers',
  },
  {
    // id: 2244,
    category: 'Travel & Transportation',
    name: 'Technician-Air Instrum/Avion',
    value: 'Technician-Air Instrum/Avion',
  },
  {
    // id: 2272,
    category: 'Travel & Transportation',
    name: 'Air Traffic Control/Related',
    value: 'Air Traffic Control/Related',
  },
  {
    // id: 2273,
    category: 'Travel & Transportation',
    name: 'Officer-Deck/Water Transport',
    value: 'Officer-Deck/Water Transport',
  },
  {
    // id: 2275,
    category: 'Travel & Transportation',
    name: 'Railway/Marine Traf Contrllrs',
    value: 'Railway/Marine Traf Contrllrs',
  },
  {
    // id: 6431,
    category: 'Travel & Transportation',
    name: 'Counsellors-Travel',
    value: 'Counsellors-Travel',
  },
  {
    // id: 6432,
    category: 'Travel & Transportation',
    name: 'Attendant-Pursers/Flight',
    value: 'Attendant-Pursers/Flight',
  },
  {
    // id: 6433,
    category: 'Travel & Transportation',
    name: 'Agent-Airline Sales/Service',
    value: 'Agent-Airline Sales/Service',
  },
  {
    // id: 6434,
    category: 'Travel & Transportation',
    name: 'Agent-Ticket/Cargo Service',
    value: 'Agent-Ticket/Cargo Service',
  },
  {
    // id: 6441,
    category: 'Travel & Transportation',
    name: 'Guides-Tour/Travel',
    value: 'Guides-Tour/Travel',
  },
  {
    // id: 6672,
    category: 'Travel & Transportation',
    name: 'Attendant-Accommodation/Travel',
    value: 'Attendant-Accommodation/Travel',
  },
  {
    // id: 7221,
    category: 'Travel & Transportation',
    name: 'Mgr-Railway Transport Oper',
    value: 'Mgr-Railway Transport Oper',
  },
  {
    // id: 7222,
    category: 'Travel & Transportation',
    name: 'Mgr-Motor/Ground Transit Oper',
    value: 'Mgr-Motor/Ground Transit Oper',
  },
  {
    // id: 7314,
    category: 'Travel & Transportation',
    name: 'Railway Carmen/women',
    value: 'Railway Carmen/women',
  },
  {
    // id: 7315,
    category: 'Travel & Transportation',
    name: 'Aircraft mechanics/ Inspectors',
    value: 'Aircraft mechanics/ Inspectors',
  },
  {
    // id: 7361,
    category: 'Travel & Transportation',
    name: 'Engineer-Railway/Yard Train',
    value: 'Engineer-Railway/Yard Train',
  },
  {
    // id: 7362,
    category: 'Travel & Transportation',
    name: 'Railway Conductors/Brakemen',
    value: 'Railway Conductors/Brakemen',
  },
  {
    // id: 7412,
    category: 'Travel & Transportation',
    name: 'Bus/Subway/Other drivers',
    value: 'Bus/Subway/Other drivers',
  },
  {
    // id: 7413,
    category: 'Travel & Transportation',
    name: 'Taxi/Limousine/Chauffeurs',
    value: 'Taxi/Limousine/Chauffeurs',
  },
  {
    // id: 7431,
    category: 'Travel & Transportation',
    name: 'Railway Yard Workers',
    value: 'Railway Yard Workers',
  },
  {
    // id: 7432,
    category: 'Travel & Transportation',
    name: 'Railway Track Maintenance Work',
    value: 'Railway Track Maintenance Work',
  },
  {
    // id: 7433,
    category: 'Travel & Transportation',
    name: 'Deck Crew/Water Transport',
    value: 'Deck Crew/Water Transport',
  },
  {
    // id: 7434,
    category: 'Travel & Transportation',
    name: 'Engine Room Crew/Water Transp',
    value: 'Engine Room Crew/Water Transp',
  },
  {
    // id: 7435,
    category: 'Travel & Transportation',
    name: 'Operator-Lock/Cable Ferry',
    value: 'Operator-Lock/Cable Ferry',
  },
  {
    // id: 7436,
    category: 'Travel & Transportation',
    name: 'Operator-Boat',
    value: 'Operator-Boat',
  },
  {
    // id: 7437,
    category: 'Travel & Transportation',
    name: 'Attendant-Air Transport Ramp',
    value: 'Attendant-Air Transport Ramp',
  },
  {
    // id: 7622,
    category: 'Travel & Transportation',
    name: 'Railway/Motor Transport Labour',
    value: 'Railway/Motor Transport Labour',
  },
  {
    // id: 9936,
    category: 'Travel & Transportation',
    name: 'Bus Owner - Transport',
    value: 'Bus Owner - Transport',
  },

  {
    // id: 131,
    category: 'Utilities',
    name: 'Mgr-TeleComm. Carriers',
    value: 'Mgr-TeleComm. Carriers',
  },
  {
    // id: 912,
    category: 'Utilities',
    name: 'Mgr-Utilities',
    value: 'Mgr-Utilities',
  },
  {
    // id: 1424,
    category: 'Utilities',
    name: 'Telephone Operator',
    value: 'Telephone Operator',
  },
  {
    // id: 7244,
    category: 'Utilities',
    name: 'Electrical Power Line Workers',
    value: 'Electrical Power Line Workers',
  },
  {
    // id: 7245,
    category: 'Utilities',
    name: 'TeleComm Line/Cable Workers',
    value: 'TeleComm Line/Cable Workers',
  },
  {
    // id: 7246,
    category: 'Utilities',
    name: 'TeleComm Installer/Repairer',
    value: 'TeleComm Installer/Repairer',
  },
  {
    // id: 7247,
    category: 'Utilities',
    name: 'Cable Television Service Tech',
    value: 'Cable Television Service Tech',
  },

  {
    // id: 7216,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Contractor-Mgr/Mechanic',
    value: 'Contractor-Mgr/Mechanic',
  },
  {
    // id: 7312,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Heavy-Duty equip mechanic',
    value: 'Heavy-Duty equip mechanic',
  },
  {
    // id: 7321,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Auto Truck Bus mechanic',
    value: 'Auto Truck Bus mechanic',
  },
  {
    // id: 7322,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Motor Vehicle/Machine Bodywork',
    value: 'Motor Vehicle/Machine Bodywork',
  },
  {
    // id: 7332,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Electrical Appliance Repairer',
    value: 'Electrical Appliance Repairer',
  },
  {
    // id: 7333,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Electrical',
    value: 'Mechanic-Electrical',
  },
  {
    // id: 7334,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Motorcycle/Other',
    value: 'Mechanic-Motorcycle/Other',
  },
  {
    // id: 7335,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Mechanic-Small Engine/equip',
    value: 'Mechanic-Small Engine/equip',
  },
  {
    // id: 7443,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Auto Mech Installers/Service',
    value: 'Auto Mech Installers/Service',
  },
  {
    // id: 7445,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Other Repairers/Servicer',
    value: 'Other Repairers/Servicer',
  },
  {
    // id: 9937,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Bus Owner - Vehicle Repair',
    value: 'Bus Owner - Vehicle Repair',
  },
  {
    // id: 9938,
    category: 'Vehicle, Appliance & Machine Repairs',
    name: 'Bus Owner - Machine Repair',
    value: 'Bus Owner - Machine Repair',
  },
];
