export const GET_APP_CONFIG_SUCCESS = 'GET_APP_CONFIG_SUCCESS';
export const RESET_APP_CONFIG_SUCCESS = 'RESET_APP_CONFIG_SUCCESS';

export const GET_WORKBENCH_CONFIG_SUCCESS = 'GET_WORKBENCH_CONFIG_SUCCESS';
export const RESET_WORKBENCH_CONFIG_SUCCESS = 'RESET_WORKBENCH_CONFIG_SUCCESS';
